### PR TITLE
Fix poweredExtraction/Insert and add simulate mode.

### LINKED ISSUE #3595: Dupe Bug involving ME Fluid Terminal
#### Description

When extracting and inserting fluids from an ME Fluid Terminal, it is expected to give and take 1000mb. 
Currently, it gives and takes 169mb.
In conjunction with tanks from other mods, this results in a dupe bug, as they insert the proper value.
#### Environment

- Minecraft Version: 1.12 (multiplayer server)
- AE2 Version: rv6 alpha 1
- Forge Version: 14.23.4.2705

Modlist: 
image

this was tested with:
EnderIO's iron tank
Mekanism's basic tank

### PR DESCRIPTION
**Pull request by fscan**
Use it in fluid terminal.

Fixes #3595

### CODE REVIEW

File: src/main/java/appeng/fluids/container/ContainerFluidTerminal.java [hunk 1]
```diff
@@ -355,20 +354,19 @@ public void doAction( EntityPlayerMP player, InventoryAction action, int slot, l
...
-			throw new NullPointerException( held.getDisplayName() + " did not give FLUID_HANDLER_ITEM_CAPABILITY" );
+			// only fluid handlers items
+			return;
 		}
-		boolean isBucket = held.getItem() == Items.BUCKET ||
-				held.getItem() == Items.WATER_BUCKET ||
-				held.getItem() == Items.LAVA_BUCKET ||
-				held.getItem() == Items.MILK_BUCKET ||
-				held.getItem() == ForgeModContainer.getInstance().universalBucket;
+		boolean isBucket = held.getItem() == Items.BUCKET || held.getItem() == Items.WATER_BUCKET || held.getItem() == Items.LAVA_BUCKET || held
```
Comment (orod-org) [inline src/main/java/appeng/fluids/container/ContainerFluidTerminal.java]: CRITICAL Reduce the number of conditional operators (4) used in the expression (maximum allowed 3). [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS1067)

File: src/main/java/appeng/util/Platform.java [hunk 2]
```diff
@@ -1182,29 +1187,39 @@ public static long nanoTime()
...
+				if( ret != null )
+				{
+					src.player().ifPresent( player -> Stats.ItemsExtracted.addToPlayer( player, (int) ret.getStackSize() ) );
+				}
+				return ret;
+			}
+			else
 			{
-				src.player().ifPresent( player -> Stats.ItemsExtracted.addToPlayer( player, (int) ret.getStackSize() ) );
+				return possible.setStackSize( itemToExtract );
```
Comment (orod-org) [inline src/main/java/appeng/util/Platform.java]: MAJOR A "NullPointerException" could be thrown; "possible" is nullable here. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS2259)

**Comment by orod-org** [comment]
SonarQube analysis reported 34 issues
* ![BLOCKER][BLOCKER] 1 blocker
* ![CRITICAL][CRITICAL] 13 critical
* ![MAJOR][MAJOR] 16 major
* ![MINOR][MINOR] 4 minor

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![BLOCKER][BLOCKER] [ContainerFluidTerminal.java#](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/8680d75489589918dee86029d013e4193d8aab4d/src/main/java/appeng/fluids/container/ContainerFluidTerminal.java#): Add or update the header of this file. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS1451)
1. ![CRITICAL][CRITICAL] [ContainerFluidTerminal.java#L122](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/8680d75489589918dee86029d013e4193d8aab4d/src/main/java/appeng/fluids/container/ContainerFluidTerminal.java#L122): Refactor this code to not nest more than 3 if/for/while/switch/try statements. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS134)
1. ![CRITICAL][CRITICAL] [ContainerFluidTerminal.java#L135](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/8680d75489589918dee86029d013e4193d8aab4d/src/main/java/appeng/fluids/container/ContainerFluidTerminal.java#L135): Refactor this code to not nest more than 3 if/for/while/switch/try statements. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS134)
1. ![CRITICAL][CRITICAL] [ContainerFluidTerminal.java#L207](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/8680d75489589918dee86029d013e4193d8aab4d/src/main/java/appeng/fluids/container/ContainerFluidTerminal.java#L207): Refactor this code to not nest more than 3 if/for/while/switch/try statements. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS134)
1. ![CRITICAL][CRITICAL] [ContainerFluidTerminal.java#L268](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/8680d75489589918dee86029d013e4193d8aab4d/src/main/java/appeng/fluids/container/ContainerFluidTerminal.java#L268): The Cyclomatic Complexity of this method "detectAndSendChanges" is 13 which is greater than 10 authorized. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AMethodCyclomaticComplexity)
1. ![CRITICAL][CRITICAL] [ContainerFluidTerminal.java#L285](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/8680d75489589918dee86029d013e4193d8aab4d/src/main/java/appeng/fluids/container/ContainerFluidTerminal.java#L285): Refactor this code to not nest more than 3 if/for/while/switch/try statements. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS134)
1. ![CRITICAL][CRITICAL] [ContainerFluidTerminal.java#L310](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/8680d75489589918dee86029d013e4193d8aab4d/src/main/java/appeng/fluids/container/ContainerFluidTerminal.java#L310): Refactor this code to not nest more than 3 if/for/while/switch/try statements. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS134)
1. ![CRITICAL][CRITICAL] [ContainerFluidTerminal.java#L324](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/8680d75489589918dee86029d013e4193d8aab4d/src/main/java/appeng/fluids/container/ContainerFluidTerminal.java#L324): Refactor this code to not nest more than 3 if/for/while/switch/try statements. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS134)
1. ![CRITICAL][CRITICAL] [ContainerFluidTerminal.java#L349](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/8680d75489589918dee86029d013e4193d8aab4d/src/main/java/appeng/fluids/container/ContainerFluidTerminal.java#L349): The Cyclomatic Complexity of this method "doAction" is 27 which is greater than 10 authorized. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AMethodCyclomaticComplexity)
1. ![CRITICAL][CRITICAL] [Platform.java#L517](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/8680d75489589918dee86029d013e4193d8aab4d/src/main/java/appeng/util/Platform.java#L517): Refactor this code to not nest more than 3 if/for/while/switch/try statements. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS134)

[BLOCKER]: https://sonarsource.github.io/sonar-github/severity-blocker.png 'Severity: BLOCKER'
[CRITICAL]: https://sonarsource.github.io/sonar-github/severity-critical.png 'Severity: CRITICAL'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'
