### PR TITLE
Implement IItemHandler capability for TileInscriber to Fix Pipe Interaction Issues

### LINKED ISSUE #2500: Inscribers not going past 21 percent
I am using the latest build for 1.10.2 downloaded it today.  I have a series of inscribers that I have tried to power just about every way I can think of.  I have used ae2 and know how it all works.  When I give it power via enderIO conduits the inscribers get to 21 percent and reset.  I also have tried powering them directly with the energy acceptor and it still did not work.  Any ideas why its not finishing the crafting process?

### PR DESCRIPTION
**Pull request by shartte**
Fixes #2500: Implement an IItemHandler that doesn't allow new items to be inserted if there's already an item in the slot, while not resetting progress.

### CODE REVIEW

File: src/main/java/appeng/tile/misc/TileInscriber.java [hunk 1]
```diff
@@ -22,7 +22,6 @@
 import java.io.IOException;
 import java.util.EnumSet;
 import java.util.List;
-
 import javax.annotation.Nullable;
```
Comment (orod-org) [inline src/main/java/appeng/tile/misc/TileInscriber.java]: MINOR 'javax.annotation.Nullable' should be separated from previous imports. [rule](https://sonar.orod.org/coding_rules#rule_key=checkstyle%3Acom.puppycrawl.tools.checkstyle.checks.imports.ImportOrderCheck)

File: src/main/java/appeng/tile/misc/TileInscriber.java [hunk 2]
```diff
@@ -580,4 +625,93 @@ private void setProcessingTime( final int processingTime )
...
+				return stack;
+			}
+
+			// If there's already an item stack in the slot, we don't allow insertion and don't do any other checks
+			if( inv.getStackInSlot( insertSlot ) != null )
+			{
+				return stack;
+			}
+
+			AdaptorIInventory adapter = new AdaptorIInventory( new WrapperInventoryRange( TileInscriber.this, insertSlot, 1, true ) );
```
Comment (orod-org) [inline src/main/java/appeng/tile/misc/TileInscriber.java]: MINOR Local variable 'adapter' could be declared final [rule](https://sonar.orod.org/coding_rules#rule_key=pmd%3ALocalVariableCouldBeFinal)

File: src/main/java/appeng/tile/misc/TileInscriber.java [hunk 3]
```diff
@@ -580,4 +625,93 @@ private void setProcessingTime( final int processingTime )
...
+		public ItemStack extractItem( int slot, int amount, boolean simulate )
+		{
+			final int validExtractSlot = ( insertSlot == extractSlot ) ? 0 : 1;
+
+			if( slot != validExtractSlot || amount == 0 )
+			{
+				return null;
+			}
+
+			AdaptorIInventory adapter = new AdaptorIInventory( new WrapperInventoryRange( TileInscriber.this, extractSlot, 1, true ) );
```
Comment (orod-org) [inline src/main/java/appeng/tile/misc/TileInscriber.java]: MINOR Local variable 'adapter' could be declared final [rule](https://sonar.orod.org/coding_rules#rule_key=pmd%3ALocalVariableCouldBeFinal)

**Comment by orod-org** [comment]
SonarQube analysis reported 7 issues
* MINOR 7 minor

Watch the comments in this conversation to review them.

#### 4 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. MINOR [TileInscriber.java#L133](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/7d3464abf9c06dee791408917ba220895714f7fe/src/main/java/appeng/tile/misc/TileInscriber.java#L133): Rename this method name to match the regular expression '^[a-z][a-zA-Z0-9]*$'. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS00100)
1. MINOR [TileInscriber.java#L141](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/7d3464abf9c06dee791408917ba220895714f7fe/src/main/java/appeng/tile/misc/TileInscriber.java#L141): Rename this method name to match the regular expression '^[a-z][a-zA-Z0-9]*$'. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS00100)
1. MINOR [TileInscriber.java#L149](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/7d3464abf9c06dee791408917ba220895714f7fe/src/main/java/appeng/tile/misc/TileInscriber.java#L149): Rename this method name to match the regular expression '^[a-z][a-zA-Z0-9]*$'. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS00100)
1. MINOR [TileInscriber.java#L178](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/7d3464abf9c06dee791408917ba220895714f7fe/src/main/java/appeng/tile/misc/TileInscriber.java#L178): Rename this method name to match the regular expression '^[a-z][a-zA-Z0-9]*$'. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS00100)
