### PR TITLE
Fixes #3265: Do not strip special chars when extracting recipes.

### LINKED ISSUE #3265: Missing recipes for processors
#### Description
I can only put items in the middle slot of the inscriber. I can't put items in the top and bottom slot. I've tried putting items in the top and bottom with hoppers and itemducts, but this doesn't work either.
Also, the recipes for all the processors and processor parts aren't showing up in JEI.
#### Environment

- Minecraft Version: 1.12.2
- AE2 Version: rv5-stable-3
- Forge Version: 14.23.1.2555

### PR DESCRIPTION
**Pull request by yueh**
There is no need for URL encoding the path as it strips special chars. This needs some testing on different OSes, e.g. unsufficient stripping of the protocol part when converting it to a path/file from an URL.

### CODE REVIEW

**Comment by fscan** [comment]
Yeah, urldecode definitely wrong here. Its if encoding/decoding URL *parameters* not paths.

**Comment by orod-org** [comment]
SonarQube analysis reported 1 issue

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [RecipeResourceCopier.java#L60](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/ac825023c1600fa25757fd4f99f9637c80b3249c/src/main/java/appeng/recipes/loader/RecipeResourceCopier.java#L60): Remove this unused "UTF_8_ENCODING" private field. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS1068)

[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'

**Comment by orod-org** [comment]
SonarQube analysis reported 2 issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [RecipeResourceCopier.java#L61](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/dd5ba33388fc61d6c9e806dd22f63c74df6b52f8/src/main/java/appeng/recipes/loader/RecipeResourceCopier.java#L61): Remove this unused "UTF_8_ENCODING" private field. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS1068)
1. ![MINOR][MINOR] [RecipeResourceCopier.java#L28](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/dd5ba33388fc61d6c9e806dd22f63c74df6b52f8/src/main/java/appeng/recipes/loader/RecipeResourceCopier.java#L28): Remove this unused import 'java.net.URLDecoder'. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AUselessImportCheck)

[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

File: src/main/java/appeng/recipes/loader/RecipeResourceCopier.java [hunk 1]
```diff
@@ -225,9 +223,9 @@ private void copyFile( @Nonnull final File destination, @Nonnull final String di
 			{
 				/* A JAR path */
 				final String dirPath = dirURL.getPath();
-				final String jarPath = dirPath.substring( 5, dirPath.indexOf( '!' ) ); // strip out only
+				final String jarPath = dirPath.substring( 0, dirPath.indexOf( '!' ) ); // strip out only
 				// the JAR file
```
Comment (orod-org) [inline src/main/java/appeng/recipes/loader/RecipeResourceCopier.java]: MAJOR Replace this use of System.out or System.err by a logger. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS106)

**Comment by orod-org** [comment]
SonarQube analysis reported 1 issue
* ![MAJOR][MAJOR] 1 major

Watch the comments in this conversation to review them.

[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
