### PR TITLE
Fix shift-double click behavior

### LINKED ISSUE #3221: Double-clicking storage cells into ME Drive...
#### Description
Double-clicking storage cells into ME Drives send all the same storage cells into the ME Drive, BUT, also extract all the same storage cells from the ME Drive into your inventory.
https://youtu.be/ODmqEdz5yEY

#### Environment

- Minecraft Version: 1.12.2
- AE2 Version: rv5-stable-2
- Forge Version: 2540
- Mods: [list.txt](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/1467155/list.txt)

### PR DESCRIPTION
**Pull request by fscan**
Fixes #3221

### CODE REVIEW

File: src/main/java/appeng/client/gui/AEBaseGui.java [hunk 1]
```diff
@@ -555,11 +555,11 @@ else if( player.capabilities.isCreativeMode )
 			return;
 		}
 
-		if( !this.disableShiftClick && isShiftKeyDown() )
+		if( !this.disableShiftClick && isShiftKeyDown() && mouseButton == 0)
```
Comment (orod-org) [inline src/main/java/appeng/client/gui/AEBaseGui.java]: MINOR ')' is not preceded with whitespace. [rule](https://sonar.orod.org/coding_rules#rule_key=checkstyle%3Acom.puppycrawl.tools.checkstyle.checks.whitespace.ParenPadCheck)

**Comment by orod-org** [comment]
SonarQube analysis reported 7 issues
* ![CRITICAL][CRITICAL] 1 critical
* ![MAJOR][MAJOR] 2 major
* ![MINOR][MINOR] 4 minor

Watch the comments in this conversation to review them.

#### 6 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![CRITICAL][CRITICAL] [AEBaseGui.java#L295](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/50181541e46520f1e5f8df143074566a3a07a230/src/main/java/appeng/client/gui/AEBaseGui.java#L295): Refactor this code to not nest more than 3 if/for/while/switch/try statements. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS134)
1. ![MAJOR][MAJOR] [AEBaseGui.java#L212](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/50181541e46520f1e5f8df143074566a3a07a230/src/main/java/appeng/client/gui/AEBaseGui.java#L212): This block of commented-out lines of code should be removed. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3ACommentedOutCodeLine)
1. ![MAJOR][MAJOR] [AEBaseGui.java#L388](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/50181541e46520f1e5f8df143074566a3a07a230/src/main/java/appeng/client/gui/AEBaseGui.java#L388): Move the declaration of "player" closer to the code that uses it. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS1941)
1. ![MINOR][MINOR] [AEBaseGui.java#L96](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/50181541e46520f1e5f8df143074566a3a07a230/src/main/java/appeng/client/gui/AEBaseGui.java#L96): Rename this field "drag_click" to match the regular expression '^[a-z][a-zA-Z0-9]*$'. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS00116)
1. ![MINOR][MINOR] [AEBaseGui.java#L102](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/50181541e46520f1e5f8df143074566a3a07a230/src/main/java/appeng/client/gui/AEBaseGui.java#L102): Rename this field "dbl_whichItem" to match the regular expression '^[a-z][a-zA-Z0-9]*$'. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS00116)
1. ![MINOR][MINOR] [AEBaseGui.java#L646](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/50181541e46520f1e5f8df143074566a3a07a230/src/main/java/appeng/client/gui/AEBaseGui.java#L646): Remove this method to simply inherit it. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS1185)

[CRITICAL]: https://sonarsource.github.io/sonar-github/severity-critical.png 'Severity: CRITICAL'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by orod-org** [comment]
SonarQube analysis reported 6 issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![CRITICAL][CRITICAL] [AEBaseGui.java#L295](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/c758a99a13c67178e48ab4f409e87c5a77e5a3d5/src/main/java/appeng/client/gui/AEBaseGui.java#L295): Refactor this code to not nest more than 3 if/for/while/switch/try statements. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS134)
1. ![MAJOR][MAJOR] [AEBaseGui.java#L212](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/c758a99a13c67178e48ab4f409e87c5a77e5a3d5/src/main/java/appeng/client/gui/AEBaseGui.java#L212): This block of commented-out lines of code should be removed. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3ACommentedOutCodeLine)
1. ![MAJOR][MAJOR] [AEBaseGui.java#L388](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/c758a99a13c67178e48ab4f409e87c5a77e5a3d5/src/main/java/appeng/client/gui/AEBaseGui.java#L388): Move the declaration of "player" closer to the code that uses it. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS1941)
1. ![MINOR][MINOR] [AEBaseGui.java#L96](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/c758a99a13c67178e48ab4f409e87c5a77e5a3d5/src/main/java/appeng/client/gui/AEBaseGui.java#L96): Rename this field "drag_click" to match the regular expression '^[a-z][a-zA-Z0-9]*$'. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS00116)
1. ![MINOR][MINOR] [AEBaseGui.java#L102](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/c758a99a13c67178e48ab4f409e87c5a77e5a3d5/src/main/java/appeng/client/gui/AEBaseGui.java#L102): Rename this field "dbl_whichItem" to match the regular expression '^[a-z][a-zA-Z0-9]*$'. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS00116)
1. ![MINOR][MINOR] [AEBaseGui.java#L646](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/c758a99a13c67178e48ab4f409e87c5a77e5a3d5/src/main/java/appeng/client/gui/AEBaseGui.java#L646): Remove this method to simply inherit it. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS1185)

[CRITICAL]: https://sonarsource.github.io/sonar-github/severity-critical.png 'Severity: CRITICAL'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'
