### PR TITLE
Fixes #1905: Export bus now considers failed crafting requests

### LINKED ISSUE #1905: Export Buses not respecting failed crafting requests
Export buses do not consider failed crafting requests when adjusting their dynamic tickrate.
If a certain amount of request failed, they should slow down instead of up, which will happen when just one request did succeed.

The best approach would be use a counter, which gets increase by one for every failed request and decreased by one for every successful, and above certain thresholds no longer increase the speed or even slow them down.

Related to #1904

### PR DESCRIPTION
**Pull request by yueh**
The export bus will now no longer speed up, if more than 1 of the last
crafting requests failed and slow down, if more then 5 failed.

Some code cleanup and moved the custom iterator into the helper package
as it is clearly related to the craftingtracker and not the export bus.

Fixes #1905

### CODE REVIEW

File: src/main/java/appeng/helpers/NonNullArrayIterator.java [hunk 1]
```diff
@@ -49,8 +49,9 @@ public boolean hasNext()
 	@Override
 	public E next()
```
Comment (orod-org) [inline src/main/java/appeng/helpers/NonNullArrayIterator.java]: MAJOR Add a "NoSuchElementException" for iteration beyond the end of the collection. [rule](http://nemo.sonarqube.org/coding_rules#rule_key=squid%3AS2272)

File: src/main/java/appeng/parts/automation/PartExportBus.java [hunk 2]
```diff
@@ -381,4 +388,18 @@ private void updateSchedulingMode( SchedulingMode schedulingMode, int x )
 			this.nextSlot = ( this.nextSlot + x ) % this.availableSlots();
 		}
 	}
+
+	private TickRateModulation getFailedCraftingPenalty( int failedAttempts )
```
Comment (orod-org) [inline src/main/java/appeng/parts/automation/PartExportBus.java]: MINOR Make "getFailedCraftingPenalty" a "static" method. [rule](http://nemo.sonarqube.org/coding_rules#rule_key=squid%3AS2325)

**Comment by orod-org** [comment]
SonarQube analysis reported 2 issues:
* MAJOR 1 major
* MINOR 1 minor

Watch the comments in this conversation to review them.
