### PR TITLE
Energy cells now always hold their charge - regardless of how they are broken

### LINKED ISSUE #5750: Energy Cell doesn't hold charge when broken
The energy cell doesnt keep its charge when it's broken with a pickaxe or wrench.

### PR DESCRIPTION
**Pull request by shartte**
Fixes #5750

### CODE REVIEW

File: src/main/java/appeng/loot/ExportSettingsFunction.java [hunk 1]
```diff
@@ -0,0 +1,65 @@
...
+ */
+public class ExportSettingsFunction implements LootItemFunction {
+    public static final ResourceLocation ID = AppEng.makeId("export_settings");
+    public static final LootItemFunctionType TYPE = new LootItemFunctionType(new Serializer());
+
+    @Override
+    public ItemStack apply(ItemStack itemStack, LootContext lootContext) {
+        var blockEntity = lootContext.getParamOrNull(LootContextParams.BLOCK_ENTITY);
+        if (blockEntity instanceof AEBaseBlockEntity aeBe) {
+            aeBe.exportSettings(SettingsFrom.DISMANTLE_ITEM, itemStack.getOrCreateTag());
```
Comment (Technici4n) [inline src/main/java/appeng/loot/ExportSettingsFunction.java:36]: It could maybe be unfortunate that we create the tag in all cases?

File: src/main/java/appeng/blockentity/networking/EnergyCellBlockEntity.java [hunk 2]
```diff
@@ -121,9 +121,10 @@ public void exportSettings(SettingsFrom from, CompoundTag data) {
         super.exportSettings(from, data);
 
         if (from == SettingsFrom.DISMANTLE_ITEM) {
-            final CompoundTag tag = new CompoundTag();
-            tag.putDouble("internalCurrentPower", this.internalCurrentPower);
-            tag.putDouble("internalMaxPower", this.getInternalMaxPower()); // used for tool tip.
+            if (this.internalCurrentPower > 0) {
```
Comment (Technici4n) [inline src/main/java/appeng/blockentity/networking/EnergyCellBlockEntity.java:124]: Should probably check > 1e-9 or similar.
