### PR TITLE
Remove swingArm in IToolHammer implementation

### LINKED ISSUE #3248: [1.12.2] Crash When Using AE2 Wrenches On Itemducts
#### Description
Using the Certus Quartz or Nether Quartz Wrench on Thermal Dynamics Itemducts causes a client crash. Since other mods' wrenches that support Thermal Dynamics don't cause a crash, I am guessing that it's on AE2's end. https://pastebin.com/gXnsyHau

#### Environment
 Heavily modded Singleplayer

- Minecraft Version: 1.12.2
- AE2 Version: appliedenergistics2-rv5-stable-2
- Forge Version: 14.23.0.2552
- Thermal Dynamics: 1.12-2.3.6.13-universal

### PR DESCRIPTION
**Pull request by fscan**
Not really needed.
Fixes #3248

### CODE REVIEW

File: src/main/java/appeng/items/tools/quartz/ToolQuartzWrench.java [hunk 1]
```diff
@@ -103,14 +103,13 @@ public boolean isUsable( ItemStack item, EntityLivingBase user, Entity entity )
 	@Override
 	public void toolUsed( ItemStack item, EntityLivingBase user, BlockPos pos )
```
Comment (orod-org) [inline src/main/java/appeng/items/tools/quartz/ToolQuartzWrench.java]: CRITICAL Add a nested comment explaining why this method is empty, throw an UnsupportedOperationException or complete the implementation. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS1186)

File: src/main/java/appeng/items/tools/quartz/ToolQuartzWrench.java [hunk 2]
```diff
@@ -103,14 +103,13 @@ public boolean isUsable( ItemStack item, EntityLivingBase user, Entity entity )
...
 	{
-		user.swingArm( user.getActiveHand() );
 	}
 
 	@Override
 	public void toolUsed( ItemStack item, EntityLivingBase user, Entity entity )
```
Comment (orod-org) [inline src/main/java/appeng/items/tools/quartz/ToolQuartzWrench.java]: CRITICAL Add a nested comment explaining why this method is empty, throw an UnsupportedOperationException or complete the implementation. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS1186)

File: src/main/java/appeng/items/tools/ToolNetworkTool.java [hunk 3]
```diff
@@ -219,13 +219,11 @@ public boolean isUsable( ItemStack item, EntityLivingBase user, Entity entity )
 	@Override
 	public void toolUsed( ItemStack item, EntityLivingBase user, BlockPos pos )
 	{
-		user.swingArm( user.getActiveHand() );
 	}
 
 	@Override
 	public void toolUsed( ItemStack item, EntityLivingBase user, Entity entity )
```
Comment (orod-org) [inline src/main/java/appeng/items/tools/ToolNetworkTool.java]: CRITICAL Add a nested comment explaining why this method is empty, throw an UnsupportedOperationException or complete the implementation. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS1186)

File: src/main/java/appeng/items/tools/ToolNetworkTool.java [hunk 4]
```diff
@@ -219,13 +219,11 @@ public boolean isUsable( ItemStack item, EntityLivingBase user, Entity entity )
 	@Override
 	public void toolUsed( ItemStack item, EntityLivingBase user, BlockPos pos )
```
Comment (orod-org) [inline src/main/java/appeng/items/tools/ToolNetworkTool.java]: CRITICAL Add a nested comment explaining why this method is empty, throw an UnsupportedOperationException or complete the implementation. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS1186)

**Comment by orod-org** [comment]
SonarQube analysis reported 5 issues
* ![CRITICAL][CRITICAL] 4 critical
* ![MAJOR][MAJOR] 1 major

Watch the comments in this conversation to review them.

#### 1 extra issue

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [ToolNetworkTool.java#L143](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/0d490c3a3d1d6bb234a3486fee3bb7dae70beeca/src/main/java/appeng/items/tools/ToolNetworkTool.java#L143): Remove this unused method parameter "is". [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS1172)

[CRITICAL]: https://sonarsource.github.io/sonar-github/severity-critical.png 'Severity: CRITICAL'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
