### PR TITLE
Fix JEI crafting voiding items

### LINKED ISSUE #3049: Pattern Terminal Void Cables
#### Description
Pattern setup for Covered Cable will void Glass Cables
Pattern setup for Dense Cable will void Covered Cables

- Step by Step ([This is all the setup you need](https://gyazo.com/0eef8338877b23d1020dddec8386c77d))
- Place 1 Glass Cable in your ME Chest/Drive (Any color **EXCEPT** white will be needed for this)
- Open the Pattern Terminal
- Seach JEI for ME Covered Cable - Fluix, Open the Recipe and Press the + to move items into Pattern
- You have just voided 1 Glass Cable

Any of the Glass cable (1 per turn) **EXCEPT** the White version will be voided when you try and move the items into the Pattern Terminal to craft the Pattern. (Note: You need to clear the Pattern every time or it wont void the item.)

The same thing will happen when you try and setup a recipe for a Dense Cable.
However you will void 4 Covered Cables (since the recipe need 4 cables)
Also here the White version works like it should, all other colors will be voided.
**IF** you have White cable in your system, it will be preferred for the recipe and **NO** other cable will be voided. 

I guess this could also be an issue with JEI moving items into the Pattern Terminal and thus resulting in items being voided.

https://gyazo.com/acdb43c9ac3e6b39d30404d503f2fdb4
https://gyazo.com/7cfa96865238fda9521520575433d7b4
https://gyazo.com/24821050a82873ecf02361fcae367608

#### Environment
No error messages in any log
Singleplayer & Multiplayer (Both tested with same setup)
[Modlist](https://pastebin.com/sJvdaMT6)

- Minecraft Version: 
- AE2 Version: rv4-stable-1
- Forge Version: 12.18.3.2316

### PR DESCRIPTION
**Pull request by fscan**
fixes #3049

### CODE REVIEW

File: src/main/java/appeng/util/Platform.java [hunk 1]
```diff
@@ -1183,6 +1183,11 @@ public static long nanoTime()
 
 	public static <StackType extends IAEStack> StackType poweredExtraction( final IEnergySource energy, final IMEInventory<StackType> cell, final StackType request, final BaseActionSource src )
 	{
+		return poweredExtraction( energy, cell, request, src, Actionable.MODULATE );
+	}
+
+	public static <StackType extends IAEStack> StackType poweredExtraction( final IEnergySource energy, final IMEInventory<StackType> cell, final StackType request, final BaseActionSource src, Actionable mode )
```
Comment (orod-org) [inline src/main/java/appeng/util/Platform.java]: MINOR Rename this generic name to match the regular expression '^[A-Z][0-9]?$'. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS00119)

**Comment by orod-org** [comment]
SonarQube analysis reported 5 issues
* ![MAJOR][MAJOR] 3 major
* ![MINOR][MINOR] 2 minor

Watch the comments in this conversation to review them.

#### 4 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [Platform.java#L604](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/3084f7c796e55e555db92d12341b074d8cd80db2/src/main/java/appeng/util/Platform.java#L604): Remove this useless assignment to local variable "itemStack". [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS1854)
1. ![MAJOR][MAJOR] [Platform.java#L649](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/3084f7c796e55e555db92d12341b074d8cd80db2/src/main/java/appeng/util/Platform.java#L649): Remove this useless assignment to local variable "itemStack". [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS1854)
1. ![MAJOR][MAJOR] [Platform.java#L1668](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/3084f7c796e55e555db92d12341b074d8cd80db2/src/main/java/appeng/util/Platform.java#L1668): This block of commented-out lines of code should be removed. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3ACommentedOutCodeLine)
1. ![MINOR][MINOR] [Platform.java#L461](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/3084f7c796e55e555db92d12341b074d8cd80db2/src/main/java/appeng/util/Platform.java#L461): Remove this use of "getDrops"; it is deprecated. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3ACallToDeprecatedMethod)

[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'
