### PR TITLE
fix #5845: fix middle mouse button autocrafting request not working in survival mode

### LINKED ISSUE #5845: Using middle mouse button to request crafting doesn't work in survival mode
### Describe the bug

pressing middle mouse button only opens the craft request menu in creative mode, but not in survival mode

### How to reproduce the bug

be in survival mode
hover over a requestable item
press middle mouse button in a crafting terminal (a normal terminal should work too)
nothing happens

### Expected behavior

the amount selection menu should open independently of the gamemode

### Additional details

it works in creative mode

### Which minecraft version are you using?

1.18

### On which mod loaders does it happen?

Fabric

### Crash log

I'll upload one later if neccesary

### PR DESCRIPTION
**Pull request by DrummerMC**

### CODE REVIEW

File: src/main/java/appeng/client/gui/me/common/MEStorageScreen.java [hunk 1]
```diff
@@ -362,6 +362,16 @@ public boolean mouseClicked(double xCoord, double yCoord, int btn) {
             return true;
         }
 
+        // handler for middle mouse button crafting in survival mode
+        boolean isKeyPickItem = this.minecraft.options.keyPickItem.matchesMouse(btn);
+        if (isKeyPickItem) {
+            Slot slot = this.getSlot((int) xCoord, (int) yCoord);
+            if (isKeyPickItem && slot instanceof RepoSlot repoSlot && repoSlot.isCraftable()) {
```
Comment (shartte) [inline src/main/java/appeng/client/gui/me/common/MEStorageScreen.java:369]: The `isKeyPickItem` check is done twice

```suggestion
            if (slot instanceof RepoSlot repoSlot && repoSlot.isCraftable()) {
```

File: src/main/java/appeng/client/gui/me/common/MEStorageScreen.java [hunk 2]
```diff
@@ -362,6 +362,16 @@ public boolean mouseClicked(double xCoord, double yCoord, int btn) {
             return true;
         }
 
+        // handler for middle mouse button crafting in survival mode
+        boolean isKeyPickItem = this.minecraft.options.keyPickItem.matchesMouse(btn);
+        if (isKeyPickItem) {
```
Comment (shartte) [inline src/main/java/appeng/client/gui/me/common/MEStorageScreen.java:367]:
```suggestion
        if (this.minecraft.options.keyPickItem.matchesMouse(btn)) {
```

**Comment by shartte** [comment]
LGTM with 2 minor nitpicks
