### PR TITLE
Fixes #4893: Fix autocrafting when substitutions are used

### LINKED ISSUE #4893: Server crash when trying to autocraft pattern with substitutions
**Describe the bug**

I'm helping to test the next release of the ATM6 pack. We've updated AE2.

While trying to craft some Quartz Glass via pattern with substitutions enabled, the server crashed as soon as I submitted the crafting job. The world would not come back up and I had to restore a backup. See crash log below.

Could of course be a bad mod interaction, but I wanted to bounce the stack trace off you before I start removing 200+ mods one by one.

Just to be clear, this was an AE2 crafting recipe that was to be carried out in a molecular assembler. No actual cross-mod interaction via processing pattern or similar. The stack trace seems to point at an explosion when trying to resolve ingredients via tags.

**To Reproduce**

- Create pattern with substitutions
- Put pattern in terminal
- Submit a crafting job with said pattern

**Expected behavior**

- For the job to either submit or fail to submit

**Additional context**

Crashlog: https://hastebin.com/urezegefaj

**Environment**

- Mod pack: ATM6 1.3.8 (unreleased)

### PR DESCRIPTION
**Pull request by shartte**
I did some superficial testing of this with the cable anchor and crafting table recipes, and both cases seemed to work. But I'd say this needs more testing. However, it should at least not crash anymore. When substitutions break down, it should simply stall the crafting job now.

Fix retrieval of substitutions from a crafting pattern. Map indices from our sparse inputs to the probable indices of the crafting pattern and more gracefully handle mismatches.

When checking whether the inventory of a crafting CPU is sufficient to craft an autocrafting job, account for the new substitutions.

Fixes #4893

### CODE REVIEW

**Comment by Meowing-Cat** [comment]
When can we expect a live build? on curse etc?

**Comment by shartte** [comment]
@Meowing-Cat We don't give out dates.

File: src/main/java/appeng/me/cluster/implementations/CraftingCPUCluster.java [hunk 1]
```diff
@@ -443,38 +443,86 @@ private IGrid getGrid() {
...
+    private boolean canCraft(final ICraftingPatternDetails details) {
+
+        if (!details.isCraftable()) {
+            // Processing patterns are relatively easy
+            for (IAEItemStack input : details.getInputs()) {
+                final IAEItemStack ais = this.inventory.extractItems(input.copy(), Actionable.SIMULATE,
+                        this.machineSrc);
+                final ItemStack is = ais == null ? ItemStack.EMPTY : ais.createItemStack();
+
+                if (is.isEmpty() || is.getCount() < input.getStackSize()) {
```
Comment (yueh) [inline src/main/java/appeng/me/cluster/implementations/CraftingCPUCluster.java:455]: This is something we should test if it's needed. Calling `createItemStack()` is a bit expensive and the condition does not make use of any `ItemStack` relevant functions. So it could just be replaced by ` if (ais == null || ais.getStackSize() < input.getStackSize())`. Just needs to potentially take into account that `ItemStack` is limited to int, while `IAEStack` uses a long

Comment (shartte) [reply src/main/java/appeng/me/cluster/implementations/CraftingCPUCluster.java]: Changed

**Review by yueh — APPROVED** [review]
