### PR TITLE
Fix Facade rendering

### LINKED ISSUE #2625: Facades brighter than normal blocks
Screenshots:
http://imgur.com/a/KivwJ

- Minecraft Version: 1.10.2
- AE2 Version: rv4-alpha-6
- Forge Version: 12.18.2.2122

### LINKED ISSUE #2679: Facades facing East and North are rendering the wrong block face
#### Environment
- Mods: [list.txt](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/629596/list.txt)
- Minecraft Version: 1.10.2
- AE2 Version: alpha 8
- Forge Version: 2135

### PR DESCRIPTION
**Pull request by fscan**
UV fix based on #2941 by @MoreThanHidden
fixes #2679, fixes #2625

### CODE REVIEW

File: src/main/java/appeng/client/render/cablebus/CubeBuilder.java [hunk 1]
```diff
@@ -251,6 +257,51 @@ private UvVector getDefaultUv( EnumFacing face, TextureAtlasSprite texture, floa
 		return uv;
 	}
 
+	private UvVector getStandardUv( EnumFacing face, TextureAtlasSprite texture, float x1, float y1, float z1, float x2, float y2, float z2 )
```
Comment (orod-org) [inline src/main/java/appeng/client/render/cablebus/CubeBuilder.java]: MAJOR Method has 8 parameters, which is greater than 7 authorized. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS00107)

File: src/main/java/appeng/client/render/DelegateBakedModel.java [hunk 2]
```diff
@@ -0,0 +1,52 @@
...
+	}
+
+	@Override
+	public TextureAtlasSprite getParticleTexture()
+	{
+		return this.baseModel.getParticleTexture();
+	}
+
+	@Override
+	public ItemCameraTransforms getItemCameraTransforms()
```
Comment (orod-org) [inline src/main/java/appeng/client/render/DelegateBakedModel.java]: MINOR Don't override a deprecated method or explicitly mark it as "@Deprecated". [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3ACallToDeprecatedMethod)

File: src/main/java/appeng/client/render/DelegateBakedModel.java [hunk 3]
```diff
@@ -0,0 +1,52 @@
...
+	{
+		return this.baseModel.getItemCameraTransforms();
```
Comment (orod-org) [inline src/main/java/appeng/client/render/DelegateBakedModel.java]: MINOR Remove this use of "getItemCameraTransforms"; it is deprecated. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3ACallToDeprecatedMethod)

**Comment by orod-org** [comment]
SonarQube analysis reported 5 issues
* ![BLOCKER][BLOCKER] 1 blocker
* ![MAJOR][MAJOR] 1 major
* ![MINOR][MINOR] 3 minor

Watch the comments in this conversation to review them.

#### 2 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![BLOCKER][BLOCKER] [DelegateBakedModel.java](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/e858b1f38b67411dfd741f5e467575cebd1c84f0/src/main/java/appeng/client/render/DelegateBakedModel.java): Add or update the header of this file. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS1451)
1. ![MINOR][MINOR] [CubeBuilder.java#L337](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/e858b1f38b67411dfd741f5e467575cebd1c84f0/src/main/java/appeng/client/render/cablebus/CubeBuilder.java#L337): Declare "v" on a separate line. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS1659)

[BLOCKER]: https://sonarsource.github.io/sonar-github/severity-blocker.png 'Severity: BLOCKER'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

File: src/main/java/appeng/client/render/cablebus/FacadeBuilder.java [hunk 4]
```diff
@@ -165,16 +137,36 @@ public static TextureAtlasAndTint getSprite( IBakedModel blockModel, IBlockState
 		return firstFound;
 	}
 
-	private void addFacade( BlockRenderLayer layer, Map<EnumFacing, FacadeRenderState> facades, EnumFacing side, AEAxisAlignedBB busBounds, boolean thinFacades, boolean renderStilt, long rand, CubeBuilder builder )
+	void addStilts( BlockRenderLayer layer, Map<EnumFacing, FacadeRenderState> facadesState, List<AxisAlignedBB> partBoxes, Set<EnumFacing> sidesWithParts, long rand, List<BakedQuad> quads )
```
Comment (orod-org) [inline src/main/java/appeng/client/render/cablebus/FacadeBuilder.java]: MAJOR Remove this unused method parameter "rand". [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS1172)

File: src/main/java/appeng/tile/networking/TileCableBus.java [hunk 5]
```diff
@@ -233,7 +233,8 @@ public void onReady()
 	@Override
 	public boolean requiresTESR()
 	{
-		return this.getCableBus().isRequiresDynamicRender();
+		return true;
+		// return this.getCableBus().isRequiresDynamicRender();
```
Comment (orod-org) [inline src/main/java/appeng/tile/networking/TileCableBus.java]: MAJOR This block of commented-out lines of code should be removed. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3ACommentedOutCodeLine)

File: src/main/java/appeng/parts/CableBusContainer.java [hunk 6]
```diff
@@ -1261,6 +1261,24 @@ private FacadeRenderState getFacadeRenderState( EnumFacing side )
 			IBlockState blockState = facade.getBlockState();
 			if( blockState != null && textureItem != null )
 			{
+				try
+				{
+					blockState = blockState.getActualState( world, pos );
+				}
+				catch( Exception e )
```
Comment (orod-org) [inline src/main/java/appeng/parts/CableBusContainer.java]: MAJOR Either log or rethrow this exception. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS1166)

File: src/main/java/appeng/parts/CableBusContainer.java [hunk 7]
```diff
@@ -1261,6 +1261,24 @@ private FacadeRenderState getFacadeRenderState( EnumFacing side )
...
+				{
+					// ignore
+				}
+
+				try
+				{
+					blockState = blockState.getBlock().getExtendedState( blockState, world, pos );
+				}
+				catch( Exception e )
```
Comment (orod-org) [inline src/main/java/appeng/parts/CableBusContainer.java]: MAJOR Either log or rethrow this exception. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS1166)

File: src/main/java/appeng/client/render/tesr/CableBusFastTESR.java [hunk 8]
```diff
@@ -0,0 +1,306 @@
...
+				this.renderSegmentBlockCurrentBounds( builder, min, max, 0.0f, 0.0f, busMax.z, 16.0f, 16.0f, 16.0f );
+				this.renderSegmentBlockCurrentBounds( builder, min, max, 0.0f, 0.0f, 0.0f, 16.0f, 16.0f, busMin.z );
+				this.renderSegmentBlockCurrentBounds( builder, min, max, 0.0f, 0.0f, busMin.z, 16.0f, busMin.y, busMax.z );
+				this.renderSegmentBlockCurrentBounds( builder, min, max, 0.0f, busMax.y, busMin.z, 16.0f, 16.0f, busMax.z );
+			}
+		}
+		return ret;
+	}
+
+	private void renderSegmentBlockCurrentBounds( CubeBuilder builder, Vector3f min, Vector3f max, float minX, float minY, float minZ, float maxX, float maxY, float maxZ )
```
Comment (orod-org) [inline src/main/java/appeng/client/render/tesr/CableBusFastTESR.java]: MAJOR Method has 9 parameters, which is greater than 7 authorized. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS00107)

File: src/main/java/appeng/client/render/tesr/CableBusFastTESR.java [hunk 9]
```diff
@@ -0,0 +1,306 @@
...
+		if( blockState == null || !( blockState instanceof IExtendedBlockState ) )
+		{
+			return null;
+		}
+
+		IExtendedBlockState extendedBlockState = (IExtendedBlockState) blockState;
+		return extendedBlockState.getValue( BlockCableBus.RENDER_STATE_PROPERTY );
+	}
+
+	private List<BakedQuad> addFacade( BlockRenderLayer layer, Map<EnumFacing, FacadeRenderState> facades, EnumFacing side, AEAxisAlignedBB busBounds, boolean thinFacades, long rand )
```
Comment (orod-org) [inline src/main/java/appeng/client/render/tesr/CableBusFastTESR.java]: CRITICAL The Cyclomatic Complexity of this method "addFacade" is 30 which is greater than 10 authorized. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AMethodCyclomaticComplexity)

File: src/main/java/appeng/client/render/tesr/CableBusFastTESR.java [hunk 10]
```diff
@@ -0,0 +1,306 @@
...
+		catch( Exception e )
+		{
+			// ignore
+		}
+
+		try
+		{
+			blockState = blockState.getBlock().getExtendedState( blockState, world, pos );
+		}
+		catch( Exception e )
```
Comment (orod-org) [inline src/main/java/appeng/client/render/tesr/CableBusFastTESR.java]: MAJOR Either log or rethrow this exception. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS1166)

File: src/main/java/appeng/client/render/tesr/CableBusFastTESR.java [hunk 11]
```diff
@@ -0,0 +1,306 @@
...
+
+				builder.setTexture( facing, spriteAndTint.getSprite() );
+			}
+			else
+			{
+				builder.setColor( color );
+			}
+		}
+
+		// builder.setDrawFaces( facadeState.getOpenFaces() );
```
Comment (orod-org) [inline src/main/java/appeng/client/render/tesr/CableBusFastTESR.java]: MAJOR This block of commented-out lines of code should be removed. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3ACommentedOutCodeLine)

File: src/main/java/appeng/client/render/tesr/CableBusFastTESR.java [hunk 12]
```diff
@@ -0,0 +1,306 @@
...
+		if( translucent )
+		{
+			color = 0x4CFFFFFF;
+		}
+		else
+		{
+			color = 0xFFFFFFFF;
+		}
+
+		// TODO: Cache this
```
Comment (orod-org) [inline src/main/java/appeng/client/render/tesr/CableBusFastTESR.java]: INFO Complete the task associated to this TODO comment. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS1135)

File: src/main/java/appeng/client/render/tesr/CableBusFastTESR.java [hunk 13]
```diff
@@ -0,0 +1,306 @@
...
+		return extendedBlockState.getValue( BlockCableBus.RENDER_STATE_PROPERTY );
+	}
+
+	private List<BakedQuad> addFacade( BlockRenderLayer layer, Map<EnumFacing, FacadeRenderState> facades, EnumFacing side, AEAxisAlignedBB busBounds, boolean thinFacades, long rand )
+	{
+		ArrayList<BakedQuad> ret = new ArrayList<>();
+
+		CubeBuilder builder = new CubeBuilder( DefaultVertexFormats.ITEM, ret );
+		FacadeRenderState facadeState = facades.get( side );
+		IBlockState blockState = facadeState.getSourceBlock();
```
Comment (orod-org) [inline src/main/java/appeng/client/render/tesr/CableBusFastTESR.java]: MAJOR Move the declaration of "blockState" closer to the code that uses it. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS1941)

File: src/main/java/appeng/client/render/tesr/CableBusFastTESR.java [hunk 14]
```diff
@@ -0,0 +1,306 @@
...
+		CableBusRenderState renderState = getRenderingState( world, pos );
+		if( renderState == null )
+		{
+			return;
+		}
+
+		boolean thinFacades = FacadeBuilder.isUseThinFacades( renderState.getBoundingBoxes() );
+		long rand = MathHelper.getPositionRandom( pos );
+
+		renderState.getFacades().forEach( ( side, state ) ->
```
Comment (orod-org) [inline src/main/java/appeng/client/render/tesr/CableBusFastTESR.java]: MAJOR Reduce this lambda expression number of lines from 23 to at most 20. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS1188)

File: src/main/java/appeng/client/render/tesr/CableBusFastTESR.java [hunk 15]
```diff
@@ -0,0 +1,306 @@
...
+	}
+
+	private static CableBusRenderState getRenderingState( final IBlockAccess world, BlockPos pos )
+	{
+		IBlockState blockState = world.getBlockState( pos );
+		try
+		{
+			blockState = blockState.getActualState( world, pos );
+		}
+		catch( Exception e )
```
Comment (orod-org) [inline src/main/java/appeng/client/render/tesr/CableBusFastTESR.java]: MAJOR Either log or rethrow this exception. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS1166)

**Comment by orod-org** [comment]
SonarQube analysis reported 26 issues
* ![BLOCKER][BLOCKER] 2 blocker
* ![CRITICAL][CRITICAL] 6 critical
* ![MAJOR][MAJOR] 12 major
* ![MINOR][MINOR] 5 minor
* ![INFO][INFO] 1 info

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![BLOCKER][BLOCKER] [DelegateBakedModel.java](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/87cd8b7c19214ffe45c627aaf64e54126150b633/src/main/java/appeng/client/render/DelegateBakedModel.java): Add or update the header of this file. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS1451)
1. ![BLOCKER][BLOCKER] [CableBusFastTESR.java](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/87cd8b7c19214ffe45c627aaf64e54126150b633/src/main/java/appeng/client/render/tesr/CableBusFastTESR.java): Add or update the header of this file. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS1451)
1. ![CRITICAL][CRITICAL] [CableBusBakedModel.java#L135](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/87cd8b7c19214ffe45c627aaf64e54126150b633/src/main/java/appeng/client/render/cablebus/CableBusBakedModel.java#L135): The Cyclomatic Complexity of this method "isStraightLine" is 12 which is greater than 10 authorized. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AMethodCyclomaticComplexity)
1. ![CRITICAL][CRITICAL] [ApiBlocks.java#L285](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/87cd8b7c19214ffe45c627aaf64e54126150b633/src/main/java/appeng/core/api/definitions/ApiBlocks.java#L285): Define a constant instead of duplicating this literal "sky_stone_chest" 3 times. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS1192)
1. ![CRITICAL][CRITICAL] [ApiBlocks.java#L344](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/87cd8b7c19214ffe45c627aaf64e54126150b633/src/main/java/appeng/core/api/definitions/ApiBlocks.java#L344): Define a constant instead of duplicating this literal "quantum_ring" 3 times. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS1192)
1. ![CRITICAL][CRITICAL] [ApiBlocks.java#L428](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/87cd8b7c19214ffe45c627aaf64e54126150b633/src/main/java/appeng/core/api/definitions/ApiBlocks.java#L428): Define a constant instead of duplicating this literal "crafting_unit" 4 times. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS1192)
1. ![CRITICAL][CRITICAL] [ApiBlocks.java#L440](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/87cd8b7c19214ffe45c627aaf64e54126150b633/src/main/java/appeng/core/api/definitions/ApiBlocks.java#L440): Define a constant instead of duplicating this literal "crafting_storage" 4 times. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS1192)
1. ![MAJOR][MAJOR] [ApiBlocks.java#L537](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/87cd8b7c19214ffe45c627aaf64e54126150b633/src/main/java/appeng/core/api/definitions/ApiBlocks.java#L537): Call "Optional#isPresent()" before accessing the value. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS3655)
1. ![MINOR][MINOR] [BlockCableBus.java#L190](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/87cd8b7c19214ffe45c627aaf64e54126150b633/src/main/java/appeng/block/networking/BlockCableBus.java#L190): Don't override a deprecated method or explicitly mark it as "@Deprecated". [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3ACallToDeprecatedMethod)
1. ![MINOR][MINOR] [CableBusBakedModel.java#L361](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/87cd8b7c19214ffe45c627aaf64e54126150b633/src/main/java/appeng/client/render/cablebus/CableBusBakedModel.java#L361): Don't override a deprecated method or explicitly mark it as "@Deprecated". [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3ACallToDeprecatedMethod)

[BLOCKER]: https://sonarsource.github.io/sonar-github/severity-blocker.png 'Severity: BLOCKER'
[CRITICAL]: https://sonarsource.github.io/sonar-github/severity-critical.png 'Severity: CRITICAL'
[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

File: src/main/java/appeng/tile/networking/CableBusTESR.java [hunk 16]
```diff
@@ -21,14 +21,16 @@
...
 import appeng.api.parts.IPart;
 import appeng.tile.AEBaseTile;
 
 
+@SideOnly( Side.CLIENT )
 public class CableBusTESR extends TileEntitySpecialRenderer<AEBaseTile>
 {
-
 	@Override
 	public void render( AEBaseTile te, double x, double y, double z, float partialTicks, int destroyStage, float p_render_10_ )
```
Comment (orod-org) [inline src/main/java/appeng/tile/networking/CableBusTESR.java]: MINOR Rename this local variable to match the regular expression '^[a-z][a-zA-Z0-9]*$'. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS00117)

**Comment by orod-org** [comment]
SonarQube analysis reported 27 issues
* ![BLOCKER][BLOCKER] 2 blocker
* ![CRITICAL][CRITICAL] 6 critical
* ![MAJOR][MAJOR] 12 major
* ![MINOR][MINOR] 6 minor
* ![INFO][INFO] 1 info

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![BLOCKER][BLOCKER] [DelegateBakedModel.java](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/d575f2a7221e8d0d28adbb9aad374b69dc1a7dce/src/main/java/appeng/client/render/DelegateBakedModel.java): Add or update the header of this file. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS1451)
1. ![BLOCKER][BLOCKER] [CableBusFastTESR.java](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/d575f2a7221e8d0d28adbb9aad374b69dc1a7dce/src/main/java/appeng/client/render/tesr/CableBusFastTESR.java): Add or update the header of this file. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS1451)
1. ![CRITICAL][CRITICAL] [CableBusBakedModel.java#L135](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/d575f2a7221e8d0d28adbb9aad374b69dc1a7dce/src/main/java/appeng/client/render/cablebus/CableBusBakedModel.java#L135): The Cyclomatic Complexity of this method "isStraightLine" is 12 which is greater than 10 authorized. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AMethodCyclomaticComplexity)
1. ![CRITICAL][CRITICAL] [ApiBlocks.java#L285](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/d575f2a7221e8d0d28adbb9aad374b69dc1a7dce/src/main/java/appeng/core/api/definitions/ApiBlocks.java#L285): Define a constant instead of duplicating this literal "sky_stone_chest" 3 times. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS1192)
1. ![CRITICAL][CRITICAL] [ApiBlocks.java#L344](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/d575f2a7221e8d0d28adbb9aad374b69dc1a7dce/src/main/java/appeng/core/api/definitions/ApiBlocks.java#L344): Define a constant instead of duplicating this literal "quantum_ring" 3 times. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS1192)
1. ![CRITICAL][CRITICAL] [ApiBlocks.java#L428](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/d575f2a7221e8d0d28adbb9aad374b69dc1a7dce/src/main/java/appeng/core/api/definitions/ApiBlocks.java#L428): Define a constant instead of duplicating this literal "crafting_unit" 4 times. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS1192)
1. ![CRITICAL][CRITICAL] [ApiBlocks.java#L440](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/d575f2a7221e8d0d28adbb9aad374b69dc1a7dce/src/main/java/appeng/core/api/definitions/ApiBlocks.java#L440): Define a constant instead of duplicating this literal "crafting_storage" 4 times. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS1192)
1. ![MAJOR][MAJOR] [ApiBlocks.java#L537](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/d575f2a7221e8d0d28adbb9aad374b69dc1a7dce/src/main/java/appeng/core/api/definitions/ApiBlocks.java#L537): Call "Optional#isPresent()" before accessing the value. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS3655)
1. ![MINOR][MINOR] [BlockCableBus.java#L190](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/d575f2a7221e8d0d28adbb9aad374b69dc1a7dce/src/main/java/appeng/block/networking/BlockCableBus.java#L190): Don't override a deprecated method or explicitly mark it as "@Deprecated". [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3ACallToDeprecatedMethod)
1. ![MINOR][MINOR] [CableBusBakedModel.java#L361](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/d575f2a7221e8d0d28adbb9aad374b69dc1a7dce/src/main/java/appeng/client/render/cablebus/CableBusBakedModel.java#L361): Don't override a deprecated method or explicitly mark it as "@Deprecated". [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3ACallToDeprecatedMethod)

[BLOCKER]: https://sonarsource.github.io/sonar-github/severity-blocker.png 'Severity: BLOCKER'
[CRITICAL]: https://sonarsource.github.io/sonar-github/severity-critical.png 'Severity: CRITICAL'
[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

File: src/main/java/appeng/parts/CableBusContainer.java [hunk 17]
```diff
@@ -1251,7 +1251,7 @@ public CableBusRenderState getRenderState()
 		return renderState;
 	}
 
-	private FacadeRenderState getFacadeRenderState( EnumFacing side )
+	private FacadeRenderState getFacadeRenderState( IBlockAccess world, BlockPos pos, EnumFacing side )
```
Comment (orod-org) [inline src/main/java/appeng/parts/CableBusContainer.java]: MAJOR Remove this unused method parameter "world". [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS1172)

**Comment by orod-org** [comment]
SonarQube analysis reported 26 issues
* ![BLOCKER][BLOCKER] 2 blocker
* ![CRITICAL][CRITICAL] 6 critical
* ![MAJOR][MAJOR] 11 major
* ![MINOR][MINOR] 6 minor
* ![INFO][INFO] 1 info

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![BLOCKER][BLOCKER] [DelegateBakedModel.java](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/55f6eafe547cbe5f2bdb92c2ffb9c3b2112602a9/src/main/java/appeng/client/render/DelegateBakedModel.java): Add or update the header of this file. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS1451)
1. ![BLOCKER][BLOCKER] [CableBusFastTESR.java](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/55f6eafe547cbe5f2bdb92c2ffb9c3b2112602a9/src/main/java/appeng/client/render/tesr/CableBusFastTESR.java): Add or update the header of this file. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS1451)
1. ![CRITICAL][CRITICAL] [CableBusBakedModel.java#L135](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/55f6eafe547cbe5f2bdb92c2ffb9c3b2112602a9/src/main/java/appeng/client/render/cablebus/CableBusBakedModel.java#L135): The Cyclomatic Complexity of this method "isStraightLine" is 12 which is greater than 10 authorized. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AMethodCyclomaticComplexity)
1. ![CRITICAL][CRITICAL] [ApiBlocks.java#L285](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/55f6eafe547cbe5f2bdb92c2ffb9c3b2112602a9/src/main/java/appeng/core/api/definitions/ApiBlocks.java#L285): Define a constant instead of duplicating this literal "sky_stone_chest" 3 times. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS1192)
1. ![CRITICAL][CRITICAL] [ApiBlocks.java#L344](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/55f6eafe547cbe5f2bdb92c2ffb9c3b2112602a9/src/main/java/appeng/core/api/definitions/ApiBlocks.java#L344): Define a constant instead of duplicating this literal "quantum_ring" 3 times. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS1192)
1. ![CRITICAL][CRITICAL] [ApiBlocks.java#L428](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/55f6eafe547cbe5f2bdb92c2ffb9c3b2112602a9/src/main/java/appeng/core/api/definitions/ApiBlocks.java#L428): Define a constant instead of duplicating this literal "crafting_unit" 4 times. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS1192)
1. ![CRITICAL][CRITICAL] [ApiBlocks.java#L440](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/55f6eafe547cbe5f2bdb92c2ffb9c3b2112602a9/src/main/java/appeng/core/api/definitions/ApiBlocks.java#L440): Define a constant instead of duplicating this literal "crafting_storage" 4 times. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS1192)
1. ![MAJOR][MAJOR] [ApiBlocks.java#L537](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/55f6eafe547cbe5f2bdb92c2ffb9c3b2112602a9/src/main/java/appeng/core/api/definitions/ApiBlocks.java#L537): Call "Optional#isPresent()" before accessing the value. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS3655)
1. ![MINOR][MINOR] [BlockCableBus.java#L190](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/55f6eafe547cbe5f2bdb92c2ffb9c3b2112602a9/src/main/java/appeng/block/networking/BlockCableBus.java#L190): Don't override a deprecated method or explicitly mark it as "@Deprecated". [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3ACallToDeprecatedMethod)
1. ![MINOR][MINOR] [CableBusBakedModel.java#L361](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/55f6eafe547cbe5f2bdb92c2ffb9c3b2112602a9/src/main/java/appeng/client/render/cablebus/CableBusBakedModel.java#L361): Don't override a deprecated method or explicitly mark it as "@Deprecated". [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3ACallToDeprecatedMethod)

[BLOCKER]: https://sonarsource.github.io/sonar-github/severity-blocker.png 'Severity: BLOCKER'
[CRITICAL]: https://sonarsource.github.io/sonar-github/severity-critical.png 'Severity: CRITICAL'
[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by orod-org** [comment]
SonarQube analysis reported 8 issues
* ![BLOCKER][BLOCKER] 1 blocker
* ![CRITICAL][CRITICAL] 1 critical
* ![MAJOR][MAJOR] 1 major
* ![MINOR][MINOR] 5 minor

Watch the comments in this conversation to review them.

#### 5 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![BLOCKER][BLOCKER] [DelegateBakedModel.java](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/1fd493ea6f45a7249928f4a7a079c54b5c56d558/src/main/java/appeng/client/render/DelegateBakedModel.java): Add or update the header of this file. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS1451)
1. ![CRITICAL][CRITICAL] [CableBusBakedModel.java#L135](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/1fd493ea6f45a7249928f4a7a079c54b5c56d558/src/main/java/appeng/client/render/cablebus/CableBusBakedModel.java#L135): The Cyclomatic Complexity of this method "isStraightLine" is 12 which is greater than 10 authorized. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AMethodCyclomaticComplexity)
1. ![MINOR][MINOR] [BlockCableBus.java#L188](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/1fd493ea6f45a7249928f4a7a079c54b5c56d558/src/main/java/appeng/block/networking/BlockCableBus.java#L188): Don't override a deprecated method or explicitly mark it as "@Deprecated". [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3ACallToDeprecatedMethod)
1. ![MINOR][MINOR] [CableBusBakedModel.java#L361](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/1fd493ea6f45a7249928f4a7a079c54b5c56d558/src/main/java/appeng/client/render/cablebus/CableBusBakedModel.java#L361): Don't override a deprecated method or explicitly mark it as "@Deprecated". [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3ACallToDeprecatedMethod)
1. ![MINOR][MINOR] [CubeBuilder.java#L338](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/1fd493ea6f45a7249928f4a7a079c54b5c56d558/src/main/java/appeng/client/render/cablebus/CubeBuilder.java#L338): Declare "v" on a separate line. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS1659)

[BLOCKER]: https://sonarsource.github.io/sonar-github/severity-blocker.png 'Severity: BLOCKER'
[CRITICAL]: https://sonarsource.github.io/sonar-github/severity-critical.png 'Severity: CRITICAL'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by fscan** [comment]
Still some issues:
1) when block emits light shading gets disabled (eg: terminal part). Not sure what to do about it.
2) blocks with multiple texture layers (eg: some chisel blocks) only use the first texture. Would have to render the quads into a buffer and use that as a texture. Not exactly sure how hard it would be.

**Comment by orod-org** [comment]
SonarQube analysis reported 7 issues
* ![CRITICAL][CRITICAL] 1 critical
* ![MAJOR][MAJOR] 1 major
* ![MINOR][MINOR] 5 minor

Watch the comments in this conversation to review them.

#### 4 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![CRITICAL][CRITICAL] [CableBusBakedModel.java#L135](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/c6ae0814ad3350e9041e0379e3c460bfa9d41214/src/main/java/appeng/client/render/cablebus/CableBusBakedModel.java#L135): The Cyclomatic Complexity of this method "isStraightLine" is 12 which is greater than 10 authorized. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AMethodCyclomaticComplexity)
1. ![MINOR][MINOR] [BlockCableBus.java#L188](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/c6ae0814ad3350e9041e0379e3c460bfa9d41214/src/main/java/appeng/block/networking/BlockCableBus.java#L188): Don't override a deprecated method or explicitly mark it as "@Deprecated". [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3ACallToDeprecatedMethod)
1. ![MINOR][MINOR] [CableBusBakedModel.java#L361](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/c6ae0814ad3350e9041e0379e3c460bfa9d41214/src/main/java/appeng/client/render/cablebus/CableBusBakedModel.java#L361): Don't override a deprecated method or explicitly mark it as "@Deprecated". [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3ACallToDeprecatedMethod)
1. ![MINOR][MINOR] [CubeBuilder.java#L338](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/c6ae0814ad3350e9041e0379e3c460bfa9d41214/src/main/java/appeng/client/render/cablebus/CubeBuilder.java#L338): Declare "v" on a separate line. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS1659)

[CRITICAL]: https://sonarsource.github.io/sonar-github/severity-critical.png 'Severity: CRITICAL'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'
