### PR TITLE
Fixes crash when either quartz types are disabled

### LINKED ISSUE #3486: cascading worldgen lag on world creation (server) (1.12.2) (rv5 stable 11)
#### Description
[21:47:55] [Server thread/WARN] [FML]: Applied Energistics 2 loaded a new chunk [-2, 16] in dimension 0 (overworld) while populating chunk [-2, 15], causing cascading worldgen lag.
[21:47:55] [Server thread/WARN] [FML]: Please report this to the mod's issue tracker. This log can be disabled in the Forge config.

#### Environment
-Multiplayer.
-In forge server console.
*Edit: seems to happen when someone is loading new chunks.
[15:49:48] [Server thread/WARN] [FML]: Applied Energistics 2 loaded a new chunk [71, -34] in dimension 7 (twilight_forest) while populating chunk [70, -34], causing cascading worldgen lag.

- Minecraft Version: "1.12.2"
- AE2 Version: "appliedenergistics2-rv5-stable-11"
- Forge Version: "forge-1.12.2-14.23.3.2655-universal"

### LINKED ISSUE #3535: Crash constructing QuartzWorldGen with B:ChargedCertusOre=false in config
I want to keep `CertusQuartzWorldGen` enabled but disable `ChargedCertusOre`. With this combination of configuration settings, loading ae2 crashes with a `NullPointerException` on [QuartzWorldGen.java:55](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/3e09c49e030e096c35328b1215b2d655c2660253/src/main/java/appeng/worldgen/QuartzWorldGen.java#L55).

- Minecraft Version: 1.12.2
- AE2 Version: stable rv5-stable-11 for Forge 14.23.1.2554
- Forge Version: 14.23.4.2707

[crash-2018-06-10_22.40.56-client.txt](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/2088582/crash-2018-06-10_22.40.56-client.txt)

### PR DESCRIPTION
**Pull request by fscan**
Also prevent cascading worldgen.
This fixes #3535, fixes #3486

### CODE REVIEW

File: src/main/java/appeng/worldgen/QuartzWorldGen.java [hunk 1]
```diff
@@ -67,26 +72,31 @@ public void generate( final Random r, final int chunkX, final int chunkZ, final
...
+				final int cx = chunkX * 16 + r.nextInt( 16 );
 				final int cy = r.nextInt( 40 * seaLevel / 64 ) + r.nextInt( 22 * seaLevel / 64 ) + 12 * seaLevel / 64;
-				final int cz = chunkZ * 16 + r.nextInt( 22 );
+				final int cz = chunkZ * 16 + r.nextInt( 16 );
 				whichOre.generate( w, r, new BlockPos( cx, cy, cz ) );
 			}
 		}
 	}
+
+	private static boolean ShouldGenerate( final boolean isCharged, final World w )
```
Comment (orod-org) [inline src/main/java/appeng/worldgen/QuartzWorldGen.java]: MINOR Rename this method name to match the regular expression '^[a-z][a-zA-Z0-9]*$'. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS00100)

**Comment by orod-org** [comment]
SonarQube analysis reported 1 issue
* ![MINOR][MINOR] 1 minor

Watch the comments in this conversation to review them.

[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'
