### PR TITLE
Replaced Watcher using Collection with a more fitting interface

### LINKED ISSUE #229: Level Emitter not working correctly
When 2 level emitters on the same network are configured to use energy mode, and have the same value specified only the first one to register will work, while the other one will do nothing.  If you change the numbers so they are off by 1 then they both will work

### PR DESCRIPTION
**Pull request by yueh**
Fixes #229.

### CODE REVIEW

File: src/main/java/appeng/me/energy/EnergyThreshold.java [hunk 1]
```diff
@@ -20,50 +20,84 @@
...
+		if( obj == null )
+			return false;
+		if( getClass() != obj.getClass() )
+			return false;
+		EnergyThreshold other = (EnergyThreshold) obj;
+		if( Double.doubleToLongBits( threshold ) != Double.doubleToLongBits( other.threshold ) )
+			return false;
+		if( watcher == null )
+		{
+			if( other.watcher != null )
```
Comment (orod-org) [inline src/main/java/appeng/me/energy/EnergyThreshold.java]: MINOR Missing curly brace. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS00121)

File: src/main/java/appeng/me/energy/EnergyThreshold.java [hunk 2]
```diff
@@ -20,50 +20,84 @@
...
+		result = prime * result + ( ( watcher == null ) ? 0 : watcher.hashCode() );
+		return result;
 	}
 
-	public IEnergyWatcher getWatcher()
+	@Override
+	public boolean equals( Object obj )
 	{
-		return this.watcher;
+		if( this == obj )
```
Comment (orod-org) [inline src/main/java/appeng/me/energy/EnergyThreshold.java]: MINOR Missing curly brace. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS00121)

File: src/main/java/appeng/me/energy/EnergyThreshold.java [hunk 3]
```diff
@@ -20,50 +20,84 @@
...
+			return true;
+		if( obj == null )
```
Comment (orod-org) [inline src/main/java/appeng/me/energy/EnergyThreshold.java]: MINOR Missing curly brace. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS00121)

File: src/main/java/appeng/me/energy/EnergyThreshold.java [hunk 4]
```diff
@@ -20,50 +20,84 @@
...
+			return false;
+		if( getClass() != obj.getClass() )
```
Comment (orod-org) [inline src/main/java/appeng/me/energy/EnergyThreshold.java]: MINOR Missing curly brace. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS00121)

File: src/main/java/appeng/me/energy/EnergyThreshold.java [hunk 5]
```diff
@@ -20,50 +20,84 @@
...
+			return false;
+		EnergyThreshold other = (EnergyThreshold) obj;
+		if( Double.doubleToLongBits( threshold ) != Double.doubleToLongBits( other.threshold ) )
```
Comment (orod-org) [inline src/main/java/appeng/me/energy/EnergyThreshold.java]: MINOR Missing curly brace. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS00121)

**Comment by orod-org** [comment]
SonarQube analysis reported 8 issues
* MAJOR 2 major
* MINOR 6 minor

Watch the comments in this conversation to review them.

#### 1 extra issue

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. MAJOR [CraftingGridCache.java#L485](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/281599691817c72cc34af1bcf7173577261217d8/src/main/java/appeng/me/cache/CraftingGridCache.java#L485): appeng.me.cache.CraftingGridCache.getCraftingFor(IAEItemStack, ICraftingPatternDetails, int, World) makes inefficient use of keySet iterator instead of entrySet iterator [rule](https://sonar.orod.org/coding_rules#rule_key=findbugs%3AWMI_WRONG_MAP_ITERATOR)

File: src/main/java/appeng/me/energy/EnergyWatcher.java [hunk 6]
```diff
@@ -35,170 +35,56 @@
...
-	public <T> T[] toArray( final T[] a )
-	{
-		return this.myInterests.toArray( a );
-	}
-
-	@Override
-	public boolean add( final Double e )
-	{
-		if( this.myInterests.contains( e ) )
+		if( this.myInterests.contains( Double.valueOf( amount ) ) )
```
Comment (orod-org) [inline src/main/java/appeng/me/energy/EnergyWatcher.java]: MAJOR A "Set<EnergyThreshold>" cannot contain a "Double" [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS2175)

**Comment by orod-org** [comment]
SonarQube analysis reported 8 issues
* MAJOR 2 major
* MINOR 6 minor

Watch the comments in this conversation to review them.

#### 1 extra issue

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. MAJOR [CraftingGridCache.java#L485](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/3369655a26e79cda34ef5c6ec543dc081870eb91/src/main/java/appeng/me/cache/CraftingGridCache.java#L485): appeng.me.cache.CraftingGridCache.getCraftingFor(IAEItemStack, ICraftingPatternDetails, int, World) makes inefficient use of keySet iterator instead of entrySet iterator [rule](https://sonar.orod.org/coding_rules#rule_key=findbugs%3AWMI_WRONG_MAP_ITERATOR)

**Comment by orod-org** [comment]
SonarQube analysis reported 1 issue

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. MAJOR [CraftingGridCache.java#L485](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/41e8f1744de8823a0882a78fccadb4a9b57b2c7b/src/main/java/appeng/me/cache/CraftingGridCache.java#L485): appeng.me.cache.CraftingGridCache.getCraftingFor(IAEItemStack, ICraftingPatternDetails, int, World) makes inefficient use of keySet iterator instead of entrySet iterator [rule](https://sonar.orod.org/coding_rules#rule_key=findbugs%3AWMI_WRONG_MAP_ITERATOR)
