### PR TITLE
Prevent NPE in InscriberTESR when getQuads() returns null

### LINKED ISSUE #4840: Crash when MI pipe enters inscriber
**Describe the bug**
Rendering crash when a Modern Industrialization pipe enters an inscriber.

**To Reproduce**
Place inscriber on the ground, put hoppers inputting into it, then put an MI pipe in, it will crash if it can enter.

**Additional context**
Crash report:
https://pastebin.com/d303p1eP

**Environment**
Fabric version, Specifics in the crash log.

### PR DESCRIPTION
**Pull request by Technici4n**
Closes #4840 and #4867.

### CODE REVIEW

File: src/main/java/appeng/client/render/tesr/InscriberTESR.java [hunk 1]
```diff
@@ -203,7 +205,9 @@ private void renderItem(MatrixStack ms, final ItemStack stack, final float o, Ve
             // for direction=null, while a block-model will have their faces for
             // cull-faces, but not direction=null
             BakedModel model = itemRenderer.getModels().getModel(stack);
-            if (!model.getQuads(null, null, new Random()).isEmpty()) {
+            List<BakedQuad> quads = model.getQuads(null, null, new Random());
+            // Note: quads may be null for mods implementing FabricBakedModel without caring about getQuads.
+            if (quads != null && quads.isEmpty()) {
```
Comment (shartte) [inline src/main/java/appeng/client/render/tesr/InscriberTESR.java:210]:
```suggestion
            if (quads != null && !quads.isEmpty()) {
```

Shouldn't it be !quads.isEmpty() ?
