### PR TITLE
Fix #6281: Add void and equal distribution upgrade to fluid cells

### LINKED ISSUE #6281: Overflow Destruction Card cannot be added to Fluid Storage Cells
### Describe the bug

Fluid Storage Cells (and by extension, chemical storage cells from Applied Mekanistics) do not support the Overflow Destruction Card. The only card supported by them is the Inverter Card.  

They also do not support the Equal Distribution Card.

### How to reproduce the bug

1. Install AE2
2. Place down a Cell Workbench
3. Put a Fluid Storage Cell (any size) into it
4. Attempt to upgrade with Overflow Destruction Card

### Expected behavior

The cell should support the upgrade card.

### Additional details

_No response_

### Which minecraft version are you using?

1.18

### On which mod loaders does it happen?

Forge

### Crash log

https://pastebin.com/JpMbrtBx

### PR DESCRIPTION
**Pull request by 62832**

### CODE REVIEW

File: src/main/java/appeng/init/internal/InitUpgrades.java [hunk 1]
```diff
@@ -77,15 +78,24 @@ public static void init() {
             Upgrades.add(AEItems.VOID_CARD, itemCell, 1, storageCellGroup);
         }
 
+        var fluidCells = List.of(
+                AEItems.FLUID_CELL_1K, AEItems.FLUID_CELL_4K, AEItems.FLUID_CELL_16K, AEItems.FLUID_CELL_64K,
+                AEItems.ITEM_CELL_256K);
```
Comment (Technici4n) [inline src/main/java/appeng/init/internal/InitUpgrades.java:83]: still got an item cell there, is this intended?

**Review by Technici4n — CHANGES_REQUESTED** [review]
Please also make sure to increase the number of upgrade slots in the config, otherwise it's quite useless. Looks good otherwise. ;)

**Comment by 62832** [comment]
Sorted. Fluid cells should have 3 upgrades corresponding to the amount of upgrades that can be applied to them now.
