### PR TITLE
Fixes #1983: WorldData cleared too early when still needed.

### LINKED ISSUE #1983: AE2 + Compact machine : Interface pattern list not saved after server reboot
Hi,

How to reproduce
1) Create a compact machine (CM) A
2) Setup a simple AE Network in CM A (controller + ME Drive + interface terminal)
3) Create a compact machine B and connect it to the network in CM A
4) In CM B setup some ME interfaces + molecular assembler
5) Go back in CM A and check the interface terminal, you'll see your new interfaces
6) Create a new pattern and add it to the molecular assembler's interfaces via the interface terminal
7) Restart the server
8) The item pattern in the molecular assembler's interfaces disappear

### PR DESCRIPTION
**Pull request by yueh**
The `WorldData` instance is removed too early during the server stop and not once the server is actually stopped.
This results in interdimensional networks to not be saved correctly as they no longer can access the `StorageData` to determine their grid.

Moved the cleanup to `FMLServerStoppedEvent` stage and extended the interface for `IWorldData` to contain a method this stage.

### CODE REVIEW

File: src/main/java/appeng/core/AppEng.java [hunk 1]
```diff
@@ -233,6 +235,12 @@ private void serverAboutToStart( final FMLServerAboutToStartEvent evt )
 	private void serverStopping( final FMLServerStoppingEvent event )
 	{
 		WorldData.instance().onServerStopping();
+	}
+
+	@EventHandler
+	private void serverStopped( final FMLServerStoppedEvent event )
```
Comment (orod-org) [inline src/main/java/appeng/core/AppEng.java]: MAJOR Remove the unused method parameter(s) "event". [rule](http://nemo.sonarqube.org/coding_rules#rule_key=squid%3AS1172)
MAJOR Private method 'serverStopped' is never used. [rule](http://nemo.sonarqube.org/coding_rules#rule_key=squid%3AUnusedPrivateMethod)

**Comment by orod-org** [comment]
SonarQube analysis reported 2 issues:
* MAJOR 2 major

Watch the comments in this conversation to review them.

File: src/main/java/appeng/core/AppEng.java (hunk 1 above)
Comment (thatsIch) [inline src/main/java/appeng/core/AppEng.java]: I dont think that annotated methods should be major problems
