### PR TITLE
More seamless recoloring of cables.

### LINKED ISSUE #5999: Using the color applicator causes a network reboot even if connections don't change
### Describe the bug

Using the color applicator causes a network reboot even if connections don't change

### How to reproduce the bug

1. Place a cable attached to a powered network
2. Use a color applicator to change its colour
3. See WAILA/WTHIT reboot

### Expected behavior

If the cable doesn't change adjacent connections, the network shouldn't bother rebooting

### Additional details

_No response_

### Which minecraft version are you using?

1.18

### On which mod loaders does it happen?

Fabric

### Crash log

N/A

### PR DESCRIPTION
**Pull request by shartte**
Do not replace the cable parts, instead just replace the part item and reset the grid color. Also sever existing, now incompatible connections if the node changes color.

Fixes #5999

### CODE REVIEW

File: src/main/java/appeng/parts/networking/CablePart.java [hunk 1]
```diff
@@ -132,7 +132,10 @@ public boolean changeColor(AEColor newColor, Player who) {
                     return true;
                 }
 
-                this.getHost().replacePart(newPart, null, who, null);
+                setPartItem(newPart);
+
+                getMainNode().setGridColor(getCableColor());
+                getHost().markForUpdate();
```
Comment (Technici4n) [inline src/main/java/appeng/parts/networking/CablePart.java:138]: Should this also markForSave?

Comment (shartte) [reply src/main/java/appeng/parts/networking/CablePart.java:138]: Good find, yes it should
