### PR TITLE
Performance improvements for the energygrid

### LINKED ISSUE #1004: Potential stackoverflow in EnergyGridCache
This affects a least `EnergyGridCache.extractAEPower()` as well as EnergyGridCache.injectAEPower()`.

It is mostly a theoretical issue and probably will not show up with normal use, but it is not outside of survival. The log itself is truncated and shows about 500 grids, but I would except that it occurs somewhere between 1k and 2k grids.

A 10x10x10 Cube of cables + quartz fiber connections might be enough.
So not to hard to obtain (1k cables + 3k quartz fiber) after a certain point and can be easily build with something like the BC builder.

The actual issue is the used recursion to visit the grids.
Changing it to a proper BFS/DFS approach using an explicit queue or stack (not the normal call stack) should mostly solve it. Changing it to a proper tail recursion might be also an idea, if possible.

It will also make the world impossible to load the world after the first crash.
But there is not log, just a notice that a stackoverflow occurred during the loading of the dimension.
Other methods beside inject/extract in `EnergyGridCache` are following the same pattern, but this could potentially be located somewhere else.

Obligatory log: http://pastebin.com/KChDsBjs

### PR DESCRIPTION
**Pull request by yueh**
Reworked the old recursive approach to a queue based loop.
Extract will try to prefer the next grid with the hightest amount of stored energy.
Inject will try to prefer the grid with the lowest percentage stored.
Other operations are first come, first serve.

----
Edit

This replaces the old not really working buffer with a special
IAEPowerStorage acting as buffer/proxy for the local energy demand as
well as temporary overflow should something provide more energy than
requested.

Currently it set to hold a maximum of 1000 AE (+ optional overflow until
consumed). It will only be used locally, no other grid can use it to
avoid starving the neighbor grids before finding a energy cell.

1000 AE is certainl excessive for a local storage in nearly all cases. Around 10 to 100 would certainly be more fitting. But a local network with 8 drives full of 64k cells will extract about 180 AE per tick, which should be about the amount a local buffer should provide to avoid reaching out to energy cells in other grids. Thus 200 AE might be fine.

Another idea might be to link it to the idle drain. So every gridnode would add/remove their idle draw to the maximum on top off a small buffer to accomendate for the energy use by channels.
---

Fixes #1004

### CODE REVIEW

File: src/main/java/appeng/me/cache/EnergyGridCache.java [hunk 1]
```diff
@@ -59,14 +64,32 @@
 public class EnergyGridCache implements IEnergyGrid
 {
 
+	private static final Comparator<IEnergyGridProvider> COMPARATOR_HIGHEST_AMOUNT_STORED_FIRST = new Comparator<IEnergyGridProvider>()
```
Comment (orod-org) [inline src/main/java/appeng/me/cache/EnergyGridCache.java]: MAJOR Make this anonymous inner class a lambda [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS1604)

File: src/main/java/appeng/me/cache/EnergyGridCache.java [hunk 2]
```diff
@@ -468,8 +459,32 @@ public boolean isNetworkPowered()
...
+
+		double leftover = amt;
+
+		while( !toVisit.isEmpty() && leftover > 0 )
+		{
+			final IEnergyGridProvider next = toVisit.poll();
+			visited.add( next );
+
+			final double cannotHold = next.injectProviderPower( amt, Actionable.SIMULATE, visited );
+			leftover = next.injectProviderPower( leftover - cannotHold, mode, visited );
```
Comment (orod-org) [inline src/main/java/appeng/me/cache/EnergyGridCache.java]: MAJOR Remove this useless assignment to local variable "leftover". [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS1854)

File: src/main/java/appeng/me/cache/EnergyGridCache.java [hunk 3]
```diff
@@ -59,14 +64,32 @@
...
 
+	private static final Comparator<IEnergyGridProvider> COMPARATOR_HIGHEST_AMOUNT_STORED_FIRST = new Comparator<IEnergyGridProvider>()
+	{
+		public int compare( IEnergyGridProvider o1, IEnergyGridProvider o2 )
+		{
+			return Double.compare( o2.getProviderStoredEnergy(), o1.getProviderStoredEnergy() );
+		}
+	};
+
+	private static final Comparator<IEnergyGridProvider> COMPARATOR_LOWEST_PERCENTAGE_FIRST = new Comparator<IEnergyGridProvider>()
```
Comment (orod-org) [inline src/main/java/appeng/me/cache/EnergyGridCache.java]: MAJOR Make this anonymous inner class a lambda [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS1604)

File: src/main/java/appeng/me/cache/EnergyGridCache.java [hunk 4]
```diff
@@ -468,8 +459,32 @@ public boolean isNetworkPowered()
 	@Override
 	public double injectPower( final double amt, final Actionable mode )
 	{
-		this.localSeen.clear();
-		return this.injectAEPower( amt, mode, this.localSeen );
+		final Queue<IEnergyGridProvider> toVisit = new PriorityQueue<>(COMPARATOR_LOWEST_PERCENTAGE_FIRST);
```
Comment (orod-org) [inline src/main/java/appeng/me/cache/EnergyGridCache.java]: MINOR '(' is not followed by whitespace. [rule](https://sonar.orod.org/coding_rules#rule_key=checkstyle%3Acom.puppycrawl.tools.checkstyle.checks.whitespace.ParenPadCheck)
MINOR ')' is not preceded with whitespace. [rule](https://sonar.orod.org/coding_rules#rule_key=checkstyle%3Acom.puppycrawl.tools.checkstyle.checks.whitespace.ParenPadCheck)

File: src/main/java/appeng/parts/networking/PartQuartzFiber.java [hunk 5]
```diff
@@ -209,7 +241,8 @@ public double getEnergyDemand( final double amt, final Set<IEnergyGrid> seen )
 		try
 		{
 			final IEnergyGrid eg = this.outerProxy.getEnergy();
-			demand += eg.getEnergyDemand( amt - demand, seen );
+			if( !seen.contains( eg ) )
```
Comment (orod-org) [inline src/main/java/appeng/parts/networking/PartQuartzFiber.java]: MINOR Missing curly brace. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS00121)

File: src/main/java/appeng/parts/networking/PartQuartzFiber.java [hunk 6]
```diff
@@ -179,27 +212,26 @@ public double injectAEPower( final double amt, final Actionable mode, final Set<
 		{
 			final IEnergyGrid eg = this.outerProxy.getEnergy();
 			if( !seen.contains( eg ) )
```
Comment (orod-org) [inline src/main/java/appeng/parts/networking/PartQuartzFiber.java]: MINOR Missing curly brace. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS00121)

File: src/main/java/appeng/parts/networking/PartQuartzFiber.java [hunk 7]
```diff
@@ -19,7 +19,10 @@
 package appeng.parts.networking;
 
 
+import java.util.Collection;
+import java.util.Collections;
```
Comment (orod-org) [inline src/main/java/appeng/parts/networking/PartQuartzFiber.java]: MINOR Remove this unused import 'java.util.Collections'. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AUselessImportCheck)

File: src/main/java/appeng/parts/networking/PartQuartzFiber.java [hunk 8]
```diff
@@ -148,7 +180,8 @@ public double extractAEPower( final double amt, final Actionable mode, final Set
 		try
 		{
 			final IEnergyGrid eg = this.outerProxy.getEnergy();
-			acquiredPower += eg.extractAEPower( amt - acquiredPower, mode, seen );
+			if( !seen.contains( eg ) )
```
Comment (orod-org) [inline src/main/java/appeng/parts/networking/PartQuartzFiber.java]: MINOR Missing curly brace. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS00121)

File: src/main/java/appeng/parts/networking/PartQuartzFiber.java [hunk 9]
```diff
@@ -179,27 +212,26 @@ public double injectAEPower( final double amt, final Actionable mode, final Set<
 		{
 			final IEnergyGrid eg = this.outerProxy.getEnergy();
 			if( !seen.contains( eg ) )
-			{
-				return eg.injectAEPower( amt, mode, seen );
-			}
+				amount = eg.injectProviderPower( amount, mode, seen );
 		}
 		catch( final GridAccessException e )
```
Comment (orod-org) [inline src/main/java/appeng/parts/networking/PartQuartzFiber.java]: MAJOR Either log or rethrow this exception. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS1166)

File: src/main/java/appeng/parts/networking/PartQuartzFiber.java [hunk 10]
```diff
@@ -179,27 +212,26 @@ public double injectAEPower( final double amt, final Actionable mode, final Set<
...
-	public double getEnergyDemand( final double amt, final Set<IEnergyGrid> seen )
+	public double getProviderEnergyDemand( final double amt, final Set<IEnergyGridProvider> seen )
 	{
 		double demand = 0;
 
 		try
 		{
 			final IEnergyGrid eg = this.getProxy().getEnergy();
-			demand += eg.getEnergyDemand( amt - demand, seen );
+			if( !seen.contains( eg ) )
```
Comment (orod-org) [inline src/main/java/appeng/parts/networking/PartQuartzFiber.java]: MINOR Missing curly brace. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS00121)

File: src/main/java/appeng/parts/networking/PartQuartzFiber.java [hunk 11]
```diff
@@ -159,16 +192,16 @@ public double extractAEPower( final double amt, final Actionable mode, final Set
...
-	public double injectAEPower( final double amt, final Actionable mode, final Set<IEnergyGrid> seen )
+	public double injectProviderPower( final double amt, final Actionable mode, final Set<IEnergyGridProvider> seen )
 	{
 
+		double amount = amt;
+
 		try
 		{
 			final IEnergyGrid eg = this.getProxy().getEnergy();
 			if( !seen.contains( eg ) )
```
Comment (orod-org) [inline src/main/java/appeng/parts/networking/PartQuartzFiber.java]: MINOR Missing curly brace. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS00121)

File: src/main/java/appeng/parts/networking/PartQuartzFiber.java [hunk 12]
```diff
@@ -179,27 +212,26 @@ public double injectAEPower( final double amt, final Actionable mode, final Set<
...
 		double demand = 0;
 
 		try
 		{
 			final IEnergyGrid eg = this.getProxy().getEnergy();
-			demand += eg.getEnergyDemand( amt - demand, seen );
+			if( !seen.contains( eg ) )
+				demand += eg.getProviderEnergyDemand( amt - demand, seen );
 		}
 		catch( final GridAccessException e )
```
Comment (orod-org) [inline src/main/java/appeng/parts/networking/PartQuartzFiber.java]: MAJOR Either log or rethrow this exception. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS1166)

File: src/main/java/appeng/parts/networking/PartQuartzFiber.java [hunk 13]
```diff
@@ -131,14 +134,43 @@ public void onPlacement( final EntityPlayer player, final EnumHand hand, final I
...
+	@Override
+	public double extractProviderPower( final double amt, final Actionable mode, final Set<IEnergyGridProvider> seen )
 	{
 		double acquiredPower = 0;
 
 		try
 		{
 			final IEnergyGrid eg = this.getProxy().getEnergy();
-			acquiredPower += eg.extractAEPower( amt - acquiredPower, mode, seen );
+			if( !seen.contains( eg ) )
```
Comment (orod-org) [inline src/main/java/appeng/parts/networking/PartQuartzFiber.java]: MINOR Missing curly brace. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS00121)

**Comment by orod-org** [comment]
SonarQube analysis reported 19 issues
* ![MAJOR][MAJOR] 8 major
* ![MINOR][MINOR] 11 minor

Watch the comments in this conversation to review them.

#### 5 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [EnergyGridCache.java#L568](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/f8a3aeed0d854425a213bfa6fdb23874a96acf76/src/main/java/appeng/me/cache/EnergyGridCache.java#L568): A "Multiset<IEnergyGridProvider>" cannot contain a "IGridHost" [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS2175)
1. ![MAJOR][MAJOR] [EnergyGridCache.java#L597](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/f8a3aeed0d854425a213bfa6fdb23874a96acf76/src/main/java/appeng/me/cache/EnergyGridCache.java#L597): A "Set<IAEPowerStorage>" cannot contain a "IGridHost" [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS2175)
1. ![MAJOR][MAJOR] [EnergyGridCache.java#L598](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/f8a3aeed0d854425a213bfa6fdb23874a96acf76/src/main/java/appeng/me/cache/EnergyGridCache.java#L598): A "Set<IAEPowerStorage>" cannot contain a "IGridHost" [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS2175)
1. ![MINOR][MINOR] [EnergyGridCache.java#L134](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/f8a3aeed0d854425a213bfa6fdb23874a96acf76/src/main/java/appeng/me/cache/EnergyGridCache.java#L134): Rename this method name to match the regular expression '^[a-z][a-zA-Z0-9]*$'. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS00100)
1. ![MINOR][MINOR] [EnergyGridCache.java#L148](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/f8a3aeed0d854425a213bfa6fdb23874a96acf76/src/main/java/appeng/me/cache/EnergyGridCache.java#L148): Rename this method name to match the regular expression '^[a-z][a-zA-Z0-9]*$'. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS00100)

[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

File: src/main/java/appeng/me/cache/EnergyGridCache.java [hunk 14]
```diff
@@ -508,8 +523,41 @@ public double getMaxStoredPower()
 	@Override
 	public double getEnergyDemand( final double maxRequired )
 	{
-		this.localSeen.clear();
-		return this.getEnergyDemand( maxRequired, this.localSeen );
+		final Queue<IEnergyGridProvider> toVisit = new LinkedList<>();
```
Comment (fscan) [inline src/main/java/appeng/me/cache/EnergyGridCache.java]: Shouldn't a stack be enough here (for better performance)? Evaluation order would differ, but i don't think it matters.

File: src/main/java/appeng/parts/networking/PartQuartzFiber.java [hunk 15]
```diff
@@ -180,26 +220,29 @@ public double injectAEPower( final double amt, final Actionable mode, final Set<
...
 		try
 		{
 			final IEnergyGrid eg = this.getProxy().getEnergy();
-			demand += eg.getEnergyDemand( amt - demand, seen );
+			if( !seen.contains( eg ) )
+			{
+				demand += eg.getProviderEnergyDemand( amt - demand, seen );
+			}
 		}
 		catch( final GridAccessException e )
```
Comment (orod-org) [inline src/main/java/appeng/parts/networking/PartQuartzFiber.java]: MAJOR Either log or rethrow this exception. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS1166)

File: src/main/java/appeng/parts/networking/PartQuartzFiber.java [hunk 16]
```diff
@@ -131,14 +133,46 @@ public void onPlacement( final EntityPlayer player, final EnumHand hand, final I
...
+		{
+			// :P
+		}
+
+		try
+		{
+			final IEnergyGrid eg = this.outerProxy.getEnergy();
+			stuff.add( eg );
+		}
+		catch( final GridAccessException e )
```
Comment (orod-org) [inline src/main/java/appeng/parts/networking/PartQuartzFiber.java]: MAJOR Either log or rethrow this exception. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS1166)

**Comment by orod-org** [comment]
SonarQube analysis reported 7 issues
* ![MAJOR][MAJOR] 5 major
* ![MINOR][MINOR] 2 minor

Watch the comments in this conversation to review them.

#### 5 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [EnergyGridCache.java#L559](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/31cb2d6611d8f04c4cb8ab8b1e32b137dd136157/src/main/java/appeng/me/cache/EnergyGridCache.java#L559): A "Multiset<IEnergyGridProvider>" cannot contain a "IGridHost" [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS2175)
1. ![MAJOR][MAJOR] [EnergyGridCache.java#L588](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/31cb2d6611d8f04c4cb8ab8b1e32b137dd136157/src/main/java/appeng/me/cache/EnergyGridCache.java#L588): A "Set<IAEPowerStorage>" cannot contain a "IGridHost" [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS2175)
1. ![MAJOR][MAJOR] [EnergyGridCache.java#L589](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/31cb2d6611d8f04c4cb8ab8b1e32b137dd136157/src/main/java/appeng/me/cache/EnergyGridCache.java#L589): A "Set<IAEPowerStorage>" cannot contain a "IGridHost" [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS2175)
1. ![MINOR][MINOR] [EnergyGridCache.java#L126](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/31cb2d6611d8f04c4cb8ab8b1e32b137dd136157/src/main/java/appeng/me/cache/EnergyGridCache.java#L126): Rename this method name to match the regular expression '^[a-z][a-zA-Z0-9]*$'. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS00100)
1. ![MINOR][MINOR] [EnergyGridCache.java#L140](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/31cb2d6611d8f04c4cb8ab8b1e32b137dd136157/src/main/java/appeng/me/cache/EnergyGridCache.java#L140): Rename this method name to match the regular expression '^[a-z][a-zA-Z0-9]*$'. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS00100)

[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

File: src/main/java/appeng/me/cache/EnergyGridCache.java [hunk 17]
```diff
@@ -643,4 +678,75 @@ public boolean unregisterEnergyInterest( final EnergyThreshold threshold )
...
+	private class GridPowerStorage implements IAEPowerStorage
+	{
+		double stored = 0;
+
+		@Override
+		public double extractAEPower( double amt, Actionable mode, PowerMultiplier usePowerMultiplier )
+		{
+			double extracted = Math.min( amt, this.stored );
+
+			if( mode == Actionable.MODULATE )
```
Comment (orod-org) [inline src/main/java/appeng/me/cache/EnergyGridCache.java]: MINOR Missing curly brace. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS00121)

File: src/main/java/appeng/me/cache/EnergyGridCache.java [hunk 18]
```diff
@@ -643,4 +678,75 @@ public boolean unregisterEnergyInterest( final EnergyThreshold threshold )
...
+		{
+			return true;
+		}
+
+		@Override
+		public double injectAEPower( double amt, Actionable mode )
+		{
+			double toStore = Math.min( amt, MAX_BUFFER_STORAGE - this.stored );
+
+			if( mode == Actionable.MODULATE )
```
Comment (orod-org) [inline src/main/java/appeng/me/cache/EnergyGridCache.java]: MINOR Missing curly brace. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS00121)

File: src/main/java/appeng/me/cache/EnergyGridCache.java [hunk 19]
```diff
@@ -643,4 +678,75 @@ public boolean unregisterEnergyInterest( final EnergyThreshold threshold )
...
+		public void setAECurrentPower( double amount )
+		{
+			this.stored = amount;
+		}
+
+		public void addAECurrentPower( double amount )
+		{
+			this.stored += amount;
+		}
+	};
```
Comment (orod-org) [inline src/main/java/appeng/me/cache/EnergyGridCache.java]: MINOR Remove this empty statement. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AEmptyStatementUsageCheck)

**Comment by orod-org** [comment]
SonarQube analysis reported 10 issues
* ![MAJOR][MAJOR] 5 major
* ![MINOR][MINOR] 5 minor

Watch the comments in this conversation to review them.

#### 5 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [EnergyGridCache.java#L554](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/15a5e9894df0840bfc9f7077b0922e6ba053e72d/src/main/java/appeng/me/cache/EnergyGridCache.java#L554): A "Multiset<IEnergyGridProvider>" cannot contain a "IGridHost" [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS2175)
1. ![MAJOR][MAJOR] [EnergyGridCache.java#L583](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/15a5e9894df0840bfc9f7077b0922e6ba053e72d/src/main/java/appeng/me/cache/EnergyGridCache.java#L583): A "Set<IAEPowerStorage>" cannot contain a "IGridHost" [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS2175)
1. ![MAJOR][MAJOR] [EnergyGridCache.java#L584](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/15a5e9894df0840bfc9f7077b0922e6ba053e72d/src/main/java/appeng/me/cache/EnergyGridCache.java#L584): A "Set<IAEPowerStorage>" cannot contain a "IGridHost" [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS2175)
1. ![MINOR][MINOR] [EnergyGridCache.java#L131](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/15a5e9894df0840bfc9f7077b0922e6ba053e72d/src/main/java/appeng/me/cache/EnergyGridCache.java#L131): Rename this method name to match the regular expression '^[a-z][a-zA-Z0-9]*$'. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS00100)
1. ![MINOR][MINOR] [EnergyGridCache.java#L145](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/15a5e9894df0840bfc9f7077b0922e6ba053e72d/src/main/java/appeng/me/cache/EnergyGridCache.java#L145): Rename this method name to match the regular expression '^[a-z][a-zA-Z0-9]*$'. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS00100)

[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by orod-org** [comment]
SonarQube analysis reported 7 issues
* ![MAJOR][MAJOR] 5 major
* ![MINOR][MINOR] 2 minor

Watch the comments in this conversation to review them.

#### 5 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [EnergyGridCache.java#L554](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/a2bd62d695ffc0da1738e64a1cf7f793be027197/src/main/java/appeng/me/cache/EnergyGridCache.java#L554): A "Multiset<IEnergyGridProvider>" cannot contain a "IGridHost" [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS2175)
1. ![MAJOR][MAJOR] [EnergyGridCache.java#L583](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/a2bd62d695ffc0da1738e64a1cf7f793be027197/src/main/java/appeng/me/cache/EnergyGridCache.java#L583): A "Set<IAEPowerStorage>" cannot contain a "IGridHost" [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS2175)
1. ![MAJOR][MAJOR] [EnergyGridCache.java#L584](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/a2bd62d695ffc0da1738e64a1cf7f793be027197/src/main/java/appeng/me/cache/EnergyGridCache.java#L584): A "Set<IAEPowerStorage>" cannot contain a "IGridHost" [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS2175)
1. ![MINOR][MINOR] [EnergyGridCache.java#L131](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/a2bd62d695ffc0da1738e64a1cf7f793be027197/src/main/java/appeng/me/cache/EnergyGridCache.java#L131): Rename this method name to match the regular expression '^[a-z][a-zA-Z0-9]*$'. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS00100)
1. ![MINOR][MINOR] [EnergyGridCache.java#L145](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/a2bd62d695ffc0da1738e64a1cf7f793be027197/src/main/java/appeng/me/cache/EnergyGridCache.java#L145): Rename this method name to match the regular expression '^[a-z][a-zA-Z0-9]*$'. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS00100)

[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by orod-org** [comment]
SonarQube analysis reported 7 issues
* ![MAJOR][MAJOR] 5 major
* ![MINOR][MINOR] 2 minor

Watch the comments in this conversation to review them.

#### 5 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [EnergyGridCache.java#L554](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/ff01ee922ad0902fdb8fa4f3889356dde4eb6ce5/src/main/java/appeng/me/cache/EnergyGridCache.java#L554): A "Multiset<IEnergyGridProvider>" cannot contain a "IGridHost" [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS2175)
1. ![MAJOR][MAJOR] [EnergyGridCache.java#L583](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/ff01ee922ad0902fdb8fa4f3889356dde4eb6ce5/src/main/java/appeng/me/cache/EnergyGridCache.java#L583): A "Set<IAEPowerStorage>" cannot contain a "IGridHost" [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS2175)
1. ![MAJOR][MAJOR] [EnergyGridCache.java#L584](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/ff01ee922ad0902fdb8fa4f3889356dde4eb6ce5/src/main/java/appeng/me/cache/EnergyGridCache.java#L584): A "Set<IAEPowerStorage>" cannot contain a "IGridHost" [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS2175)
1. ![MINOR][MINOR] [EnergyGridCache.java#L131](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/ff01ee922ad0902fdb8fa4f3889356dde4eb6ce5/src/main/java/appeng/me/cache/EnergyGridCache.java#L131): Rename this method name to match the regular expression '^[a-z][a-zA-Z0-9]*$'. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS00100)
1. ![MINOR][MINOR] [EnergyGridCache.java#L145](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/ff01ee922ad0902fdb8fa4f3889356dde4eb6ce5/src/main/java/appeng/me/cache/EnergyGridCache.java#L145): Rename this method name to match the regular expression '^[a-z][a-zA-Z0-9]*$'. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS00100)

[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

File: src/main/java/appeng/tile/powersink/AEBasePoweredTile.java [hunk 20]
```diff
@@ -123,34 +123,20 @@ public final double injectAEPower( double amt, final Actionable mode )
...
-			}
-
-			return 0;
+			this.setInternalCurrentPower( this.getInternalCurrentPower() + insertable );
 		}
+
+		return amt - insertable;
 	}
 
 	protected void PowerEvent( final PowerEventType x )
```
Comment (orod-org) [inline src/main/java/appeng/tile/powersink/AEBasePoweredTile.java]: MINOR Rename this method name to match the regular expression '^[a-z][a-zA-Z0-9]*$'. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS00100)

File: src/main/java/appeng/tile/networking/TileController.java [hunk 21]
```diff
@@ -151,12 +154,10 @@ protected double funnelPowerIntoStorage( final double power, final Actionable mo
...
 		try
 		{
-			final double ret = this.getProxy().getEnergy().injectPower( power, mode );
-			if( mode == Actionable.SIMULATE )
-			{
-				return ret;
-			}
-			return 0;
+			final IEnergyGrid grid = this.getProxy().getEnergy();
+			final double leftOver = grid.injectPower( power, mode );
```
Comment (orod-org) [inline src/main/java/appeng/tile/networking/TileController.java]: MINOR Immediately return this expression instead of assigning it to the temporary variable "leftOver". [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS1488)

File: src/main/java/appeng/tile/networking/TileEnergyAcceptor.java [hunk 22]
```diff
@@ -84,11 +85,8 @@ protected double funnelPowerIntoStorage( final double power, final Actionable mo
 		{
 			final IEnergyGrid grid = this.getProxy().getEnergy();
 			final double leftOver = grid.injectPower( power, mode );
```
Comment (orod-org) [inline src/main/java/appeng/tile/networking/TileEnergyAcceptor.java]: MINOR Immediately return this expression instead of assigning it to the temporary variable "leftOver". [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS1488)

**Comment by orod-org** [comment]
SonarQube analysis reported 20 issues
* ![MAJOR][MAJOR] 9 major
* ![MINOR][MINOR] 11 minor

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [EnergyGridCache.java#L554](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/1526b94c8c80ba81c2dcb9d482f334474580d6c7/src/main/java/appeng/me/cache/EnergyGridCache.java#L554): A "Multiset<IEnergyGridProvider>" cannot contain a "IGridHost" [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS2175)
1. ![MAJOR][MAJOR] [EnergyGridCache.java#L583](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/1526b94c8c80ba81c2dcb9d482f334474580d6c7/src/main/java/appeng/me/cache/EnergyGridCache.java#L583): A "Set<IAEPowerStorage>" cannot contain a "IGridHost" [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS2175)
1. ![MAJOR][MAJOR] [EnergyGridCache.java#L584](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/1526b94c8c80ba81c2dcb9d482f334474580d6c7/src/main/java/appeng/me/cache/EnergyGridCache.java#L584): A "Set<IAEPowerStorage>" cannot contain a "IGridHost" [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS2175)
1. ![MAJOR][MAJOR] [AEBasePoweredTile.java#L102](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/1526b94c8c80ba81c2dcb9d482f334474580d6c7/src/main/java/appeng/tile/powersink/AEBasePoweredTile.java#L102): Remove this unused method parameter "maxRequired". [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS1172)
1. ![MAJOR][MAJOR] [AEBasePoweredTile.java#L272](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/1526b94c8c80ba81c2dcb9d482f334474580d6c7/src/main/java/appeng/tile/powersink/AEBasePoweredTile.java#L272): Remove this conditional structure or edit its code blocks so that they're not all the same. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS3923)
1. ![MAJOR][MAJOR] [AEBasePoweredTile.java#L281](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/1526b94c8c80ba81c2dcb9d482f334474580d6c7/src/main/java/appeng/tile/powersink/AEBasePoweredTile.java#L281): Merge this if statement with the enclosing one. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS1066)
1. ![MAJOR][MAJOR] [AEBasePoweredTile.java#L303](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/1526b94c8c80ba81c2dcb9d482f334474580d6c7/src/main/java/appeng/tile/powersink/AEBasePoweredTile.java#L303): Merge this if statement with the enclosing one. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS1066)
1. ![MINOR][MINOR] [IC2PowerSinkAdapter.java#L66](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/1526b94c8c80ba81c2dcb9d482f334474580d6c7/src/main/java/appeng/integration/modules/ic2/IC2PowerSinkAdapter.java#L66): Remove this method to simply inherit it. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS1185)
1. ![MINOR][MINOR] [EnergyGridCache.java#L131](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/1526b94c8c80ba81c2dcb9d482f334474580d6c7/src/main/java/appeng/me/cache/EnergyGridCache.java#L131): Rename this method name to match the regular expression '^[a-z][a-zA-Z0-9]*$'. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS00100)
1. ![MINOR][MINOR] [EnergyGridCache.java#L145](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/1526b94c8c80ba81c2dcb9d482f334474580d6c7/src/main/java/appeng/me/cache/EnergyGridCache.java#L145): Rename this method name to match the regular expression '^[a-z][a-zA-Z0-9]*$'. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS00100)

[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by orod-org** [comment]
SonarQube analysis reported 17 issues
* ![MAJOR][MAJOR] 6 major
* ![MINOR][MINOR] 11 minor

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [AEBasePoweredTile.java#L102](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/e17ff34ea77a6f0f6bb3db3edc235c1a22f91208/src/main/java/appeng/tile/powersink/AEBasePoweredTile.java#L102): Remove this unused method parameter "maxRequired". [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS1172)
1. ![MAJOR][MAJOR] [AEBasePoweredTile.java#L272](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/e17ff34ea77a6f0f6bb3db3edc235c1a22f91208/src/main/java/appeng/tile/powersink/AEBasePoweredTile.java#L272): Remove this conditional structure or edit its code blocks so that they're not all the same. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS3923)
1. ![MAJOR][MAJOR] [AEBasePoweredTile.java#L281](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/e17ff34ea77a6f0f6bb3db3edc235c1a22f91208/src/main/java/appeng/tile/powersink/AEBasePoweredTile.java#L281): Merge this if statement with the enclosing one. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS1066)
1. ![MAJOR][MAJOR] [AEBasePoweredTile.java#L303](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/e17ff34ea77a6f0f6bb3db3edc235c1a22f91208/src/main/java/appeng/tile/powersink/AEBasePoweredTile.java#L303): Merge this if statement with the enclosing one. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS1066)
1. ![MINOR][MINOR] [IC2PowerSinkAdapter.java#L66](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/e17ff34ea77a6f0f6bb3db3edc235c1a22f91208/src/main/java/appeng/integration/modules/ic2/IC2PowerSinkAdapter.java#L66): Remove this method to simply inherit it. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS1185)
1. ![MINOR][MINOR] [EnergyGridCache.java#L130](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/e17ff34ea77a6f0f6bb3db3edc235c1a22f91208/src/main/java/appeng/me/cache/EnergyGridCache.java#L130): Rename this method name to match the regular expression '^[a-z][a-zA-Z0-9]*$'. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS00100)
1. ![MINOR][MINOR] [EnergyGridCache.java#L144](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/e17ff34ea77a6f0f6bb3db3edc235c1a22f91208/src/main/java/appeng/me/cache/EnergyGridCache.java#L144): Rename this method name to match the regular expression '^[a-z][a-zA-Z0-9]*$'. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS00100)
1. ![MINOR][MINOR] [TileCharger.java#L85](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/e17ff34ea77a6f0f6bb3db3edc235c1a22f91208/src/main/java/appeng/tile/misc/TileCharger.java#L85): Rename this method name to match the regular expression '^[a-z][a-zA-Z0-9]*$'. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS00100)
1. ![MINOR][MINOR] [TileCharger.java#L101](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/e17ff34ea77a6f0f6bb3db3edc235c1a22f91208/src/main/java/appeng/tile/misc/TileCharger.java#L101): Rename this method name to match the regular expression '^[a-z][a-zA-Z0-9]*$'. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS00100)
1. ![MINOR][MINOR] [AEBasePoweredTile.java#L85](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/e17ff34ea77a6f0f6bb3db3edc235c1a22f91208/src/main/java/appeng/tile/powersink/AEBasePoweredTile.java#L85): Rename this method name to match the regular expression '^[a-z][a-zA-Z0-9]*$'. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS00100)

[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'
