### PR TITLE
Fixes #1333: Updated old code parts related to recipes

### LINKED ISSUE #1333: Please refer to RecipeSorter
`[12:53:15] [Client thread/INFO] [FML]:   Unknown recipe class! appeng.recipes.game.DisassembleRecipe Modder please refer to net.minecraftforge.oredict.RecipeSorter`

This appears on loadup, but does not crash.

### PR DESCRIPTION
**Pull request by thatsIch**
Fixed an additional bug, where the disassembling recipes were not working properly. The fail logic was flawed, so that it would never match the recipe

### CODE REVIEW

File: src/main/java/appeng/core/Registration.java [hunk 1]
```diff
@@ -562,10 +561,16 @@ public void initialize( FMLInitializationEvent event )
...
+		{
+			GameRegistry.addRecipe( new DisassembleRecipe() );
+			RecipeSorter.register( "appliedenergistics2:disassemble", DisassembleRecipe.class, Category.SHAPELESS, "after:minecraft:shapeless" );
+		}
 
 		if( AEConfig.instance.isFeatureEnabled( AEFeature.enableFacadeCrafting ) )
-			CraftingManager.getInstance().getRecipeList().add( new FacadeRecipe() );
+		{
+			GameRegistry.addRecipe( new FacadeRecipe() );
+			RecipeSorter.register( "appliedenergistics2:facade", FacadeRecipe.class, Category.SHAPELESS, "after:minecraft:shapeless" );
```
Comment (yueh) [inline src/main/java/appeng/core/Registration.java]: Are facades not shaped recipes?

**Comment by thatsIch** [comment]
Changed it to shaped
