### PR TITLE
Closes #5055: Temporary load a area after a spatial transport

### LINKED ISSUE #5055: Storing a quantum bridge + spatial anchor inside a spatial storage does not work as expected
**Describe the bug**
Storing a quantum bridge + spatial anchor inside a spatial storage cell does not keep the bridge, network and anchor active and the connection to the bridge gets lost.

**To Reproduce**
Build a minimal network in the overworld consisting of:
- Controller
- Creative Energy Cell
- Spatial Anchor
- Quantum Bridge + entangled singularity
- Spatial IO Port + Spatial Cell + Button
- Spatial Pylons
- ME Crafting Terminal

Inside the SCS area build:
- Controller
- Creative Energy Cell
- Spatial Anchor
- Quantum Bridge + the other entangled singularity
- ME drive + storage cell

Go to the Terminal and put items into the Network. Check the Spatial Anchor, it should show something along the lines of "Loading/Spanning x chunks in 1 worlds". Trigger the Spatial IO Port to store the drive, bridge and anchor inside the spatial storage. Check the Terminal again, no Items are visible. Check the Spatial Anchor, it should show something along the lines of "Loading/Spanning x chunks in 1 worlds", so no change. Bring back the SCS Area from storage. The Items should show up again in inside the Terminal. Store the SCS Area again inside the storage. Use "/ae2 spatial tp 1" to teleport inside the spatial cell. Check the anchor inside the cell it now shows something like "Loading/Spanning x chunks in 2 worlds". Teleport back to the overworld with "/ae2 spatial tpback". Check the overworld anchor it now shows something like "Loading/Spanning x chunks in 2 worlds"

**Expected behavior**
When i send a anchor and a quantum bridge into spatial storage i expect the anchor to keep the chunks inside the spatial dimension loaded without the need to teleport inside the cell. The anchor in the overworld should show/update to "Loading/Spanning x chunks in 2 worlds" to signal that the bridged part inside the spatial cell is still loaded and active and it should be possible to access the items inside the drive.

**Environment**
Singleplayer/Multiplayer
F3+C crashlog: [https://pastebin.com/LYcuA0vU](https://pastebin.com/LYcuA0vU)

### PR DESCRIPTION
**Pull request by yueh**

### CODE REVIEW

File: src/main/java/appeng/tile/spatial/SpatialAnchorTileEntity.java [hunk 1]
```diff
@@ -388,4 +398,28 @@ private ServerWorld getServerWorld() {
...
+    public boolean prepareToMove() {
+        // Just in case there are still some chunks left, as the world will change.F
+        this.releaseAll();
+
+        return true;
+    }
+
+    @Override
+    public void doneMoving() {
+        // reset the init state to keep the temporary loaded area until the network ist ready.
```
Comment (shartte) [inline src/main/java/appeng/tile/spatial/SpatialAnchorTileEntity.java:412]:
```suggestion
        // reset the init state to keep the temporary loaded area until the network is ready.
```

File: src/main/java/appeng/tile/spatial/SpatialAnchorTileEntity.java [hunk 2]
```diff
@@ -388,4 +398,28 @@ private ServerWorld getServerWorld() {
...
+        this.initialized = false;
+
+        // Temporary load an area after a spatial transfer until the network is constructed and cleanup is performed.
```
Comment (shartte) [inline src/main/java/appeng/tile/spatial/SpatialAnchorTileEntity.java:415]:
```suggestion
        // Temporarily load an area after a spatial transfer until the network is constructed and cleanup is performed.
```

**Review by shartte — APPROVED** [review]

File: src/main/java/appeng/tile/spatial/SpatialAnchorTileEntity.java [hunk 3]
```diff
@@ -65,7 +66,16 @@
...
 public class SpatialAnchorTileEntity extends AENetworkTileEntity
-        implements IGridTickable, IConfigManagerHost, IConfigurableObject, IOverlayDataSource {
+        implements IGridTickable, IConfigManagerHost, IConfigurableObject, IOverlayDataSource, IMovableTile {
+
+    /**
+     * Loads this radius after being move via a spatial transfer. This accounts for the anchor not being placed in the
+     * center of the SCS, but not as much as trying to fully load a 128 cubic cell with 8x8 chunks. This would need to
+     * load a 17x17 square.
+     * 
+     * TODO: 1.17 Break API compat and pass plot id or plot-descriptor to {@link IMovableTile}.
```
Comment (yueh) [inline src/main/java/appeng/tile/spatial/SpatialAnchorTileEntity.java:76]: Does not have to be breaking. Could be a more advanced version of `IMovableTile` or `IMovableHandler`. Maybe not at tile level, but the whole SCS construct.
