### PR TITLE
Fix StorageBus not updating item count correctly

### LINKED ISSUE #3215: Compacting Drawers aren't refreshed when inserting items into AE
#### Description
When you insert items that end up in Storage Drawer's Compacting Drawers such as Iron Ingots or Coal it will not refresh the corresponding blocks/nuggets.
For example, insert 64 Coal, you will not see 7 Coal Blocks until you re-open the terminal.

#### Environment

- Minecraft Version: 1.12.2
- AE2 Version: rv5-stable-1 
- Forge Version: 2537
- Mods: [list.txt](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/1464047/list.txt)

### PR DESCRIPTION
**Pull request by fscan**
Fixes #3215

### CODE REVIEW

File: src/main/java/appeng/parts/misc/PartStorageBus.java [hunk 1]
```diff
@@ -354,12 +354,12 @@ private void resetCache()
...
 
 		final IMEInventory<IAEItemStack> out = this.getInternalHandler();
-
-		if( this.monitor != null )
-		{
-			this.monitor.onTick();
-		}
-
+		/*
+		 * if( this.monitor != null )
```
Comment (orod-org) [inline src/main/java/appeng/parts/misc/PartStorageBus.java]: MAJOR This block of commented-out lines of code should be removed. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3ACommentedOutCodeLine)

File: src/main/java/appeng/parts/misc/ItemHandlerAdapter.java [hunk 2]
```diff
@@ -91,7 +89,14 @@ public IAEItemStack injectItems( IAEItemStack iox, Actionable type, IActionSourc
 
 		if( type == Actionable.MODULATE )
 		{
-			this.onTick();
+			try
+			{
+				this.proxy.getTick().alertDevice( this.proxy.getNode() );
+			}
+			catch( GridAccessException ex )
```
Comment (orod-org) [inline src/main/java/appeng/parts/misc/ItemHandlerAdapter.java]: MAJOR Either log or rethrow this exception. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS1166)

File: src/main/java/appeng/parts/misc/ItemHandlerAdapter.java [hunk 3]
```diff
@@ -167,7 +172,14 @@ public IAEItemStack extractItems( IAEItemStack request, Actionable mode, IAction
 		{
 			if( mode == Actionable.MODULATE )
 			{
-				this.onTick();
+				try
+				{
+					this.proxy.getTick().alertDevice( this.proxy.getNode() );
+				}
+				catch( GridAccessException ex )
```
Comment (orod-org) [inline src/main/java/appeng/parts/misc/ItemHandlerAdapter.java]: MAJOR Either log or rethrow this exception. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS1166)

File: src/main/java/appeng/parts/misc/ItemHandlerAdapter.java [hunk 4]
```diff
@@ -320,39 +257,133 @@ private void postDifference( Iterable<IAEItemStack> a )
...
-		this.mySource = mySource;
-	}
+		private ItemStack[] cachedStacks = new ItemStack[0];
+		private IAEItemStack[] cachedAeStacks = new IAEItemStack[0];
+		private final IItemHandler itemHandler;
 
-	@Override
-	public IItemList<IAEItemStack> getAvailableItems( IItemList<IAEItemStack> out )
-	{
+		public InventoryCache( IItemHandler itemHandler )
```
Comment (orod-org) [inline src/main/java/appeng/parts/misc/ItemHandlerAdapter.java]: MINOR Redundant 'public' modifier. [rule](https://sonar.orod.org/coding_rules#rule_key=checkstyle%3Acom.puppycrawl.tools.checkstyle.checks.modifier.RedundantModifierCheck)

**Comment by orod-org** [comment]
SonarQube analysis reported 4 issues
* ![MAJOR][MAJOR] 3 major
* ![MINOR][MINOR] 1 minor

Watch the comments in this conversation to review them.

[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

File: src/main/java/appeng/parts/misc/PartStorageBus.java [hunk 5]
```diff
@@ -470,7 +465,7 @@ public MEInventoryHandler getInternalHandler()
 			{
 				this.checkInterfaceVsStorageBus( target, this.getSide().getOpposite() );
 
-				this.handler = new MEInventoryHandler( inv, AEApi.instance().storage().getStorageChannel( IItemStorageChannel.class ) );
+				this.handler = new MEInventoryHandler<IAEItemStack>( inv, AEApi.instance().storage().getStorageChannel( IItemStorageChannel.class ) );
```
Comment (orod-org) [inline src/main/java/appeng/parts/misc/PartStorageBus.java]: MINOR Replace the type specification in this constructor call with the diamond operator ("<>"). [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS2293)

File: src/main/java/appeng/parts/misc/ItemHandlerAdapter.java [hunk 6]
```diff
@@ -91,7 +89,14 @@ public IAEItemStack injectItems( IAEItemStack iox, Actionable type, IActionSourc
 
 		if( type == Actionable.MODULATE )
 		{
-			this.onTick();
+			try
+			{
+				this.proxyable.getProxy().getTick().alertDevice( this.proxyable.getProxy().getNode() );
+			}
+			catch( GridAccessException ex )
```
Comment (orod-org) [inline src/main/java/appeng/parts/misc/ItemHandlerAdapter.java]: MAJOR Either log or rethrow this exception. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS1166)

File: src/main/java/appeng/parts/misc/ItemHandlerAdapter.java [hunk 7]
```diff
@@ -167,7 +172,14 @@ public IAEItemStack extractItems( IAEItemStack request, Actionable mode, IAction
 		{
 			if( mode == Actionable.MODULATE )
 			{
-				this.onTick();
+				try
+				{
+					this.proxyable.getProxy().getTick().alertDevice( this.proxyable.getProxy().getNode() );
+				}
+				catch( GridAccessException ex )
```
Comment (orod-org) [inline src/main/java/appeng/parts/misc/ItemHandlerAdapter.java]: MAJOR Either log or rethrow this exception. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS1166)

**Comment by orod-org** [comment]
SonarQube analysis reported 4 issues
* ![MAJOR][MAJOR] 2 major
* ![MINOR][MINOR] 2 minor

Watch the comments in this conversation to review them.

[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'
