### PR TITLE
Fixes issues with lightmap information on Quads (Fixes #2502)

### LINKED ISSUE #2502: Controller Darkness-Lightning issue?
Forge Version: forge-1.10.2-12.18.2.2110
AE Version: https://github.com/AppliedEnergistics/Applied-Energistics-2/commit/30a978b614075b77c98bc632b16b86e184fcf170

I did not use/try OptiFine.

So on the ME Controller when turned on half of it get "somewhat dark" not sure if this is a graphic setting or a known issue or even a feature, just seemed odd:

See the red outlined areas on the NOT powered controller being evenly "lit" up
and on the POWERED controller being somewhat darkened out to the left 2/3 of it:

lightning_bug

EDIT: This is not due to the Animation, the animation goes on and the darkness stays.

### PR DESCRIPTION
**Pull request by shartte**
This reverts back to the old way of extending the vertex format with the necessary vertex element for lightmap data, if fullbright quads are enabled. Instead of then enabling the extended vertex format for Optifine, it is disabled if Optifine is detected. 

Since the root cause is actually that the Vanilla lighting pipeline doesn't support such Vertex Formats, we disable it also if the Forge lighting pipeline is disabled.

This also relates to #2489.

### CODE REVIEW

File: src/main/java/appeng/client/ClientHelper.java [hunk 1]
```diff
@@ -79,7 +81,11 @@
 	public void preinit()
 	{
 		MinecraftForge.EVENT_BUS.register( this );
-		ModelLoaderRegistry.registerLoader( UVLModelLoader.INSTANCE );
+		// Do not register the Fullbright hacks if Optifine is present or if the Forge lighting is disabled
+		if( !FMLClientHandler.instance().hasOptifine() && ForgeModContainer.forgeLightPipelineEnabled )
```
Comment (orod-org) [inline src/main/java/appeng/client/ClientHelper.java]: MAJOR Method appeng.client.ClientHelper.preinit() orders expressions in a conditional in a sub optimal way [rule](https://sonar.orod.org/coding_rules#rule_key=fb-contrib%3ASEO_SUBOPTIMAL_EXPRESSION_ORDER)

**Comment by orod-org** [comment]
SonarQube analysis reported 4 issues
* BLOCKER 1 blocker
* MAJOR 3 major

Watch the comments in this conversation to review them.

#### 2 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. BLOCKER [VertexFormats.java](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/ebc2e20d39ca95d8feb0226088dc6bc97b0ce543/src/main/java/appeng/client/render/VertexFormats.java): Add or update the header of this file. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS1451)
1. MAJOR [UVLModelLoader.java#L275](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/ebc2e20d39ca95d8feb0226088dc6bc97b0ce543/src/main/java/appeng/client/render/model/UVLModelLoader.java#L275): Method appeng.client.render.model.UVLModelLoader$UVLModelWrapper.bake(IModelState, VertexFormat, Function) appears to call the same method on the same object redundantly [rule](https://sonar.orod.org/coding_rules#rule_key=fb-contrib%3APRMC_POSSIBLY_REDUNDANT_METHOD_CALLS)

**Comment by orod-org** [comment]
SonarQube analysis reported 3 issues
* MAJOR 3 major

Watch the comments in this conversation to review them.

#### 1 extra issue

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. MAJOR [UVLModelLoader.java#L275](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/ebc2e20d39ca95d8feb0226088dc6bc97b0ce543/src/main/java/appeng/client/render/model/UVLModelLoader.java#L275): Method appeng.client.render.model.UVLModelLoader$UVLModelWrapper.bake(IModelState, VertexFormat, Function) appears to call the same method on the same object redundantly [rule](https://sonar.orod.org/coding_rules#rule_key=fb-contrib%3APRMC_POSSIBLY_REDUNDANT_METHOD_CALLS)

File: src/main/java/appeng/client/render/VertexFormats.java [hunk 2]
```diff
@@ -0,0 +1,68 @@
...
+/**
+ * Utility for managing extended Vertex Formats without having to re-clone existing vertex formats over and over again.
+ */
+public final class VertexFormats
+{
+
+	// Standard item format extended with lightmap coordinates
+	private static final VertexFormat itemFormatWithLightMap = new VertexFormat( DefaultVertexFormats.ITEM ).addElement( DefaultVertexFormats.TEX_2S );
+
+	private VertexFormats() {
```
Comment (orod-org) [inline src/main/java/appeng/client/render/VertexFormats.java]: MINOR Move this left curly brace to the beginning of next line of code. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3ALeftCurlyBraceStartLineCheck)

**Comment by orod-org** [comment]
SonarQube analysis reported 3 issues
* MAJOR 2 major
* MINOR 1 minor

Watch the comments in this conversation to review them.

#### 1 extra issue

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. MAJOR [UVLModelLoader.java#L275](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/3488f4e094819e8ef32c419b978e32a06accc53b/src/main/java/appeng/client/render/model/UVLModelLoader.java#L275): Method appeng.client.render.model.UVLModelLoader$UVLModelWrapper.bake(IModelState, VertexFormat, Function) appears to call the same method on the same object redundantly [rule](https://sonar.orod.org/coding_rules#rule_key=fb-contrib%3APRMC_POSSIBLY_REDUNDANT_METHOD_CALLS)
