### PR TITLE
Fixes #3024: Crash on recipe lookup for disabled features

### LINKED ISSUE #3024: game crash if QuartzKnife is disabled
If you disable the QuartzKnife in the configuration _B:QuartzKnife=false_ the game crashes on load.

- Minecraft Version: 1.12
- AE2 Version: rv5-alpha-2
- Forge Version: 14.21.1.2426

[crash-2017-08-11_12.16.50-client.txt](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/1217583/crash-2017-08-11_12.16.50-client.txt)

### PR DESCRIPTION
**Pull request by yueh**
Adds a new recipe condition for a single AEFeature or a list of them.
Moved the factories to their own package, in preparation of phasing out the old recipe handling.

### CODE REVIEW

File: src/main/java/appeng/recipes/factories/ingredients/PartIngredientFactory.java [hunk 1]
```diff
@@ -0,0 +1,66 @@
...
+
+public class PartIngredientFactory implements IIngredientFactory
+{
+
+	@Nonnull
+	@Override
+	public net.minecraft.item.crafting.Ingredient parse( JsonContext context, JsonObject json )
+	{
+		String partName = json.get( "part" ).getAsString();
+		Object result = (Object) Api.INSTANCE.registries().recipes().resolveItem( AppEng.MOD_ID, partName );
```
Comment (orod-org) [inline src/main/java/appeng/recipes/factories/ingredients/PartIngredientFactory.java]: MINOR Remove this unnecessary cast to "Object". [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS1905)

File: src/main/java/appeng/recipes/factories/conditions/Features.java [hunk 2]
```diff
@@ -0,0 +1,65 @@
...
+
+
+public class Features implements IConditionFactory
+{
+	@Override
+	public BooleanSupplier parse( JsonContext jsonContext, JsonObject jsonObject )
+	{
+		final boolean result;
+
+		if( JsonUtils.isJsonArray( jsonObject, "features" ) )
```
Comment (orod-org) [inline src/main/java/appeng/recipes/factories/conditions/Features.java]: CRITICAL Define a constant instead of duplicating this literal "features" 4 times. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS1192)

**Comment by orod-org** [comment]
SonarQube analysis reported 2 issues
* ![CRITICAL][CRITICAL] 1 critical
* ![MINOR][MINOR] 1 minor

Watch the comments in this conversation to review them.

[CRITICAL]: https://sonarsource.github.io/sonar-github/severity-critical.png 'Severity: CRITICAL'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by orod-org** [comment]
SonarQube analysis reported 1 issue
* ![CRITICAL][CRITICAL] 1 critical

Watch the comments in this conversation to review them.

[CRITICAL]: https://sonarsource.github.io/sonar-github/severity-critical.png 'Severity: CRITICAL'
