### PR TITLE
Fixes #1559: Level Emitter with P:R alloy wire does not crash anymore

### LINKED ISSUE #1559: Hangs the server and the load on the CPU 200%
KCauldron-1.7.10-1420.108
appliedenergistics2-rv2-stable-5

Starts the server in console writes these messages:

[20:03:51] [Server thread/INFO]: Layer: appeng/parts/layers/LayerISidedInventory_CableBusPart loaded successfully - 5282 bytes
[20:03:51] [Server thread/INFO]: Layer: appeng/parts/layers/LayerIFluidHandler_CableBusPart loaded successfully - 2442 bytes
[20:03:51] [Server thread/INFO]: Layer: appeng/parts/layers/LayerITileStorageMonitorable_CableBusPart loaded successfully - 1070 bytes
[20:03:51] [Server thread/INFO]: Layer: appeng/parts/layers/LayerIEnergySink_CableBusPart loaded successfully - 4248 bytes
[20:03:51] [Server thread/INFO]: Layer: appeng/parts/layers/LayerIEnergySource_CableBusPart loaded successfully - 4184 bytes
[20:03:51] [Server thread/INFO]: Layer: appeng/parts/layers/LayerIEnergyHandler_CableBusPart loaded successfully - 1801 bytes
[20:03:52] [Server thread/INFO]: Force loading chunk [172, 95] in class net.minecraft.world.WorldProviderSurface
[20:03:52] [Server thread/INFO]: Force loading chunk [172, 96] in class net.minecraft.world.WorldProviderSurface
[20:03:52] [Server thread/INFO]: Force loading chunk [172, 97] in class net.minecraft.world.WorldProviderSurface
[20:03:52] [Server thread/INFO]: Force loading chunk [173, 95] in class net.minecraft.world.WorldProviderSurface
[20:03:52] [Server thread/INFO]: Force loading chunk [173, 96] in class net.minecraft.world.WorldProviderSurface
[20:03:52] [Server thread/INFO]: Force loading chunk [173, 97] in class net.minecraft.world.WorldProviderSurface
[20:03:52] [Server thread/INFO]: Force loading chunk [174, 95] in class net.minecraft.world.WorldProviderSurface
[20:03:52] [Server thread/INFO]: Force loading chunk [174, 96] in class net.minecraft.world.WorldProviderSurface
[20:03:52] [Server thread/INFO]: Force loading chunk [174, 97] in class net.minecraft.world.WorldProviderSurface

Then the server crashes and ship much CPU.

### PR DESCRIPTION
**Pull request by thatsIch**
Required to implement a more advanced interface, if not done that way, the parts will update themselves recursively

### CODE REVIEW

File: src/main/java/appeng/fmp/CableBusPart.java [hunk 1]
```diff
@@ -83,24 +83,37 @@
...
-public class CableBusPart extends JCuboidPart implements JNormalOcclusion, IRedstonePart, AEMultiTile
+public class CableBusPart extends JCuboidPart implements JNormalOcclusion, IMaskedRedstonePart, AEMultiTile
 {
 
 	public static final ThreadLocal<Boolean> DISABLE_FACADE_OCCLUSION = new ThreadLocal<Boolean>();
 	private static final Cuboid6[] SIDE_TESTS = new Cuboid6[] {
 
-			new Cuboid6( 6.0 / 16.0, 0, 6.0 / 16.0, 10.0 / 16.0, 6.0 / 16.0, 10.0 / 16.0 ), // DOWN(0, -1, 0),
+			new Cuboid6( 6.0 / 16.0, 0, 6.0 / 16.0, 10.0 / 16.0, 6.0 / 16.0, 10.0 / 16.0 ),
+			// DOWN(0, -1, 0),
```
Comment (yueh) [inline src/main/java/appeng/fmp/CableBusPart.java]: The order looks a bit strange with the comment below the object.
