### PR TITLE
Fixes #2044: No longer uses internal exceptions

### LINKED ISSUE #2044: GridConnection throwing internal exception
`GridConnection` is throwing an internal exception instead of one provided by the API.
Like `FailedConnection` or a more fitting subtype.

### PR DESCRIPTION
**Pull request by yueh**
Added 3 new exception as subclass to FailedConnection to allow a more
precise handling and/or logging.

### CODE REVIEW

File: src/main/java/appeng/me/GridConnection.java [hunk 1]
```diff
@@ -24,7 +24,10 @@
 
 import net.minecraftforge.common.util.ForgeDirection;
 
+import appeng.api.exceptions.ExistingConnectionException;
 import appeng.api.exceptions.FailedConnection;
+import appeng.api.exceptions.SecurityConnectionException;
+import appeng.api.exceptions.NullNodeConnectionException;
```
Comment (orod-org) [inline src/main/java/appeng/me/GridConnection.java]: MINOR Wrong order for 'appeng.api.exceptions.NullNodeConnectionException' import. [rule](http://nemo.sonarqube.org/coding_rules#rule_key=checkstyle%3Acom.puppycrawl.tools.checkstyle.checks.imports.ImportOrderCheck)

**Comment by orod-org** [comment]
SonarQube analysis reported 1 issue:
* MINOR 1 minor

Watch the comments in this conversation to review them.
