### PR TITLE
Fixes CME in CraftingCPU cluster when moving items back into the network

### LINKED ISSUE #5109: ChainedIterator ConcurrentModificationException
ChainedIterator ConcurrentModificationException happening in ``storeItems`` in ``CraftingCPUCluster``

**Describe the bug**
Canceling a craft can cause a CME in certain situations, usually on low space

**To Reproduce**
Attached are two zipped worlds. One will crash on load with the CME, the other one 
can crash by ask for 10 vibration chambers and then cancelling the crafting on the crafting status gui.

**Expected behavior**
Not crashing

**Additional context**
Crash log
https://gist.github.com/PrototypeTrousers/5140b1b2de38e08abab9227587f6bd74#file-chainediteratorcme
The CME can be avoided by copying the list before iterating but maybe there is a proper solution
```
IItemList<IAEItemStack> iList = Api.instance().storage().getStorageChannel(IItemStorageChannel.class).createList();
this.inventory.getItemList().forEach(iList::add);
for( IAEItemStack is : iList ) {
```

**Environment**
AdoptopenJDK 8u275
version: 0bdc408e950fe787277d1e48be61ebf928127429

[Ask to craft then cancel craft to crash.zip](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/6251754/Ask.to.craft.then.cancel.craft.to.crash.zip)
[Chained CME on load.zip](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/6251755/Chained.CME.on.load.zip)

### PR DESCRIPTION
**Pull request by shartte**
Fixes #5109: Don't mutate the item list while iterating over it.

This is also slightly more optimized than the old version.

### CODE REVIEW

File: src/main/java/appeng/me/cluster/implementations/CraftingCPUCluster.java [hunk 1]
```diff
@@ -790,20 +791,21 @@ private void storeItems() {
...
+        IItemList<IAEItemStack> itemList = this.inventory.getItemList();
+        for (IAEItemStack is : itemList) {
+            this.postChange(is, this.machineSrc);
+            IAEItemStack remainder = ii.injectItems(is.copy(), Actionable.MODULATE, this.machineSrc);
 
-            if (is != null) {
-                this.inventory.injectItems(is, Actionable.MODULATE, this.machineSrc);
+            // The network was unable to receive all of the items, i.e. no or not enough storage space left
+            if (remainder != null) {
+                is.setStackSize(remainder.getStackSize());
```
Comment (yueh) [inline src/main/java/appeng/me/cluster/implementations/CraftingCPUCluster.java:801]: I am not sure how this will behave in some extreme cases like size > `Integer.MAX_VALUE`. Crafting is certainly one of the few cases, which can run into these.

Comment (shartte) [reply src/main/java/appeng/me/cluster/implementations/CraftingCPUCluster.java:801]: This is all IAEItemStack, so it should be all longs?

Comment (yueh) [reply src/main/java/appeng/me/cluster/implementations/CraftingCPUCluster.java:801]: Yes, but we should clamp these to `Integer.MAX_VALUE` when they leave the network, like being stored in an external storage. And I do not think that is actually safeguarded at all.
This is usually fine as nothing else should move more than a few k at once. Crafting is really the only case where it can actually happen. But that might already apply for the current code.

Comment (shartte) [reply src/main/java/appeng/me/cluster/implementations/CraftingCPUCluster.java:801]: Yeah it was already stored in the CPU when it gets to this point, so I don't think this is any more "unsafe" than before, really.
