### PR TITLE
Fixes #3476: Correctly handle an empty top namepress.

### LINKED ISSUE #3476: Crash with Name Inscriber Press and Inscriber
[Crashlog](https://pastebin.com/A7QZ3aAy)

Modpack: FTB Revelations 1.8.0
Minecraft Version: 1.12.2
Forge Version: 14.23.2.2627
AE Version: rv5-stable-11

Steps to replicate crash:
1. Make 2 Name Inscriber Press.
2. Place them into an Inscriber, one on the top slot and one on the bottom slot.
3. Place an ME Interface into the middle slot.
4. Remove the top Name Inscriber Press as the ME Interface is being renamed.
5. Game crashes.

Can't even load the world anymore after the crash, have to use an older backup.

### PR DESCRIPTION
**Pull request by yueh**
Also some further changes like avoiding to match a recipe without any
input.

### CODE REVIEW

File: src/main/java/appeng/tile/misc/TileInscriber.java [hunk 1]
```diff
@@ -281,25 +281,23 @@ private boolean hasWork()
 	@Nullable
 	public IInscriberRecipe getTask()
 	{
-		return getTask( this.sideItemHandler.getStackInSlot( 0 ), this.topItemHandler.getStackInSlot( 0 ), this.bottomItemHandler.getStackInSlot( 0 ) );
+		return this.getTask( this.sideItemHandler.getStackInSlot( 0 ), this.topItemHandler.getStackInSlot( 0 ), this.bottomItemHandler.getStackInSlot( 0 ) );
 	}
 
 	@Nullable
 	private IInscriberRecipe getTask( final ItemStack input, final ItemStack plateA, final ItemStack plateB )
```
Comment (orod-org) [inline src/main/java/appeng/tile/misc/TileInscriber.java]: CRITICAL The Cyclomatic Complexity of this method "getTask" is 28 which is greater than 10 authorized. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AMethodCyclomaticComplexity)

**Comment by orod-org** [comment]
SonarQube analysis reported 6 issues
* ![CRITICAL][CRITICAL] 6 critical

Watch the comments in this conversation to review them.

#### 5 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![CRITICAL][CRITICAL] [TileInscriber.java#L321](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/96901003c05437f1e13c5ba5cf4a50b2264fae43/src/main/java/appeng/tile/misc/TileInscriber.java#L321): Reduce the number of conditional operators (5) used in the expression (maximum allowed 3). [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS1067)
1. ![CRITICAL][CRITICAL] [TileInscriber.java#L326](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/96901003c05437f1e13c5ba5cf4a50b2264fae43/src/main/java/appeng/tile/misc/TileInscriber.java#L326): Reduce the number of conditional operators (5) used in the expression (maximum allowed 3). [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS1067)
1. ![CRITICAL][CRITICAL] [TileInscriber.java#L335](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/96901003c05437f1e13c5ba5cf4a50b2264fae43/src/main/java/appeng/tile/misc/TileInscriber.java#L335): Refactor this code to not nest more than 3 if/for/while/switch/try statements. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS134)
1. ![CRITICAL][CRITICAL] [TileInscriber.java#L359](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/96901003c05437f1e13c5ba5cf4a50b2264fae43/src/main/java/appeng/tile/misc/TileInscriber.java#L359): Refactor this code to not nest more than 3 if/for/while/switch/try statements. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS134)
1. ![CRITICAL][CRITICAL] [TileInscriber.java#L425](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/96901003c05437f1e13c5ba5cf4a50b2264fae43/src/main/java/appeng/tile/misc/TileInscriber.java#L425): Refactor this code to not nest more than 3 if/for/while/switch/try statements. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS134)

[CRITICAL]: https://sonarsource.github.io/sonar-github/severity-critical.png 'Severity: CRITICAL'
