### PR TITLE
Fix accelerated Export Bus Dupe Issues when Network shows items twice

### LINKED ISSUE #6294: [BUG]Copy item Bug!!!!! & the ME interface priority cannot work
### Describe the bug

You can swipe items through the input and output ports
And the me port priority is invalid
——————————————
你可以通过输入输出端口刷取物品
并且me端口优先级失效

### How to reproduce the bug

Add My Telegram and I'll send a video for you
[@](https://t.me/NatsumiXD)

### Expected behavior

priority works fine & Can't get extra items

### Additional details

_No response_

### Which minecraft version are you using?

1.18

### On which mod loaders does it happen?

Fabric

### Crash log

NO

### PR DESCRIPTION
**Pull request by shartte**
Export buses were too trusting of the simulated extraction amounts.
I.e. double chest with two storage buses over-report available items and successfully allow simulated extractions with too many items.

Fixes #6294

### CODE REVIEW

File: src/main/java/appeng/parts/automation/StorageExportStrategy.java [hunk 1]
```diff
@@ -55,26 +59,38 @@ public long transfer(StackTransferContext context, AEKey what, long amount, Acti
...
-                if (mode == Actionable.MODULATE) {
-                    StorageHelper.poweredExtraction(
-                            context.getEnergySource(),
-                            inv.getInventory(),
-                            what,
-                            wasInserted,
-                            context.getActionSource(),
-                            Actionable.MODULATE);
-                    tx.commit();
+        if (wasInserted > 0 && mode == Actionable.MODULATE) {
```
Comment (Technici4n) [inline src/main/java/appeng/parts/automation/StorageExportStrategy.java:72]: This seems to always be called with `MODULATE` by the way, not sure why we have a mode parameter there in the first place.

Comment (Technici4n) [inline src/main/java/appeng/parts/automation/StorageExportStrategy.java:72]: This seems to always be called with `MODULATE` by the way, not sure why we have a mode parameter there in the first place.

Comment (Technici4n) [reply src/main/java/appeng/parts/automation/StorageExportStrategy.java:72]: I opened a new issue for this, not going to break AppMek just for the sake of it.
