### PR TITLE
Fixes anchor rendering

### LINKED ISSUE #2664: Cable Anchors cause cables to render as if they had a side connection
#### Description

To compare here is a screenshot of how it looked in 1.7.10. So you could have cables side by side and still have them look normal.

#### Environment
[list.txt](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/619746/list.txt)

- Minecraft Version: 1.10.2
- AE2 Version: alpha 7
- Forge Version: 2135

### LINKED ISSUE #2680: Cable Anchor visible throught facades
#### Description
When moving around you can see cable anchors flickering through facades

#### Environment
- Mods: [list.txt](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/629596/list.txt)
- Minecraft Version: 1.10.2
- AE2 Version: alpha 9
- Forge Version: 2135

### PR DESCRIPTION
**Pull request by yueh**
Replaced the simple List<ResourceLocation> for the static models with a new container also indicating a solid part, which can be used to prevent the creation of an intersection.

Uses a shorter cable anchor model should a facade be present similar to the smaller collision box.

Fixes #2680 
Fixes #2664

### CODE REVIEW

File: src/main/java/appeng/parts/automation/PlaneModels.java [hunk 1]
```diff
@@ -42,34 +43,34 @@
...
-		Map<PlaneConnections, List<ResourceLocation>> modelsOn = new HashMap<>();
-		Map<PlaneConnections, List<ResourceLocation>> modelsHasChannel = new HashMap<>();
+		Map<PlaneConnections, IPartModel> modelsOff = new HashMap<>();
+		Map<PlaneConnections, IPartModel> modelsOn = new HashMap<>();
+		Map<PlaneConnections, IPartModel> modelsHasChannel = new HashMap<>();
 
 		for( PlaneConnections permutation : PlaneConnections.PERMUTATIONS )
 		{
 			ResourceLocation planeOff = new ResourceLocation( AppEng.MOD_ID, prefixOff + permutation.getFilenameSuffix() );
 			ResourceLocation planeOn = new ResourceLocation( AppEng.MOD_ID, prefixOn + permutation.getFilenameSuffix() );
```
Comment (orod-org) [inline src/main/java/appeng/parts/automation/PlaneModels.java]: MAJOR Method new appeng.parts.automation.PlaneModels(String, String) appears to call the same method on the same object redundantly [rule](https://sonar.orod.org/coding_rules#rule_key=fb-contrib%3APRMC_POSSIBLY_REDUNDANT_METHOD_CALLS)

File: src/main/java/appeng/parts/automation/PartAnnihilationPlane.java [hunk 2]
```diff
@@ -500,9 +506,11 @@ private boolean canHandleBlock( final WorldServer w, final BlockPos pos )
 		final Material material = state.getMaterial();
 		final float hardness = state.getBlockHardness( w, pos );
 		final boolean ignoreMaterials = material == Material.AIR || material == Material.LAVA || material == Material.WATER || material.isLiquid();
-		final boolean ignoreBlocks = state.getBlock() == Blocks.BEDROCK || state.getBlock() == Blocks.END_PORTAL || state.getBlock() == Blocks.END_PORTAL_FRAME || state.getBlock() == Blocks.COMMAND_BLOCK;
+		final boolean ignoreBlocks = state.getBlock() == Blocks.BEDROCK || state.getBlock() == Blocks.END_PORTAL || state
+				.getBlock() == Blocks.END_PORTAL_FRAME || state.getBlock() == Blocks.COMMAND_BLOCK;
 
-		return !ignoreMaterials && !ignoreBlocks && !w.isAirBlock( pos ) && w.isBlockLoaded( pos ) && w.canMineBlockBody( Platform.getPlayer( w ), pos ) && hardness >= 0f;
+		return !ignoreMaterials && !ignoreBlocks && !w.isAirBlock( pos ) && w.isBlockLoaded( pos ) && w.canMineBlockBody( Platform.getPlayer( w ),
```
Comment (orod-org) [inline src/main/java/appeng/parts/automation/PartAnnihilationPlane.java]: MAJOR Method appeng.parts.automation.PartAnnihilationPlane.canHandleBlock(WorldServer, BlockPos) orders expressions in a conditional in a sub optimal way [rule](https://sonar.orod.org/coding_rules#rule_key=fb-contrib%3ASEO_SUBOPTIMAL_EXPRESSION_ORDER)

File: src/main/java/appeng/client/render/cablebus/CableBusBakedModel.java [hunk 3]
```diff
@@ -176,7 +179,7 @@ private void addCableQuads( CableBusRenderState renderState, List<BakedQuad> qua
 
 		// If the connection is straight, no busses are attached, and no covered core has been forced (in case of glass
 		// cables), then render the cable as a simplified straight line.
-		boolean noAttachments = renderState.getAttachments().isEmpty();
+		boolean noAttachments = !renderState.getAttachments().entrySet().stream().filter( p -> p.getValue().isSolid() ).findAny().isPresent();
 		if( isStraightLine( cableType, connectionTypes ) && noAttachments )
```
Comment (orod-org) [inline src/main/java/appeng/client/render/cablebus/CableBusBakedModel.java]: MAJOR Method appeng.client.render.cablebus.CableBusBakedModel.addCableQuads(CableBusRenderState, List) orders expressions in a conditional in a sub optimal way [rule](https://sonar.orod.org/coding_rules#rule_key=fb-contrib%3ASEO_SUBOPTIMAL_EXPRESSION_ORDER)

File: src/main/java/appeng/parts/misc/PartInvertedToggleBus.java [hunk 4]
```diff
@@ -19,26 +19,24 @@
...
 import appeng.core.AppEng;
 import appeng.helpers.Reflected;
 import appeng.items.parts.PartModels;
+import appeng.parts.PartModel;
 
 
 public class PartInvertedToggleBus extends PartToggleBus
 {
 	@PartModels
 	public static final ResourceLocation MODEL_BASE = new ResourceLocation( AppEng.MOD_ID, "part/inverted_toggle_bus_base" );
```
Comment (orod-org) [inline src/main/java/appeng/parts/misc/PartInvertedToggleBus.java]: BLOCKER "MODEL_BASE" is the name of a field in "PartToggleBus". [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS2387)

File: src/main/java/appeng/parts/misc/PartInvertedToggleBus.java [hunk 5]
```diff
@@ -19,26 +19,24 @@
...
 
-	public static final List<ResourceLocation> MODELS_OFF = ImmutableList.of(MODEL_BASE, MODEL_STATUS_OFF);
-	public static final List<ResourceLocation> MODELS_ON = ImmutableList.of(MODEL_BASE, MODEL_STATUS_ON);
-	public static final List<ResourceLocation> MODELS_HAS_CHANNEL = ImmutableList.of(MODEL_BASE, MODEL_STATUS_HAS_CHANNEL);
+	public static final PartModel MODELS_OFF = new PartModel( MODEL_BASE, MODEL_STATUS_OFF );
```
Comment (orod-org) [inline src/main/java/appeng/parts/misc/PartInvertedToggleBus.java]: BLOCKER "MODELS_OFF" is the name of a field in "PartToggleBus". [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS2387)

File: src/main/java/appeng/parts/misc/PartInvertedToggleBus.java [hunk 6]
```diff
@@ -19,26 +19,24 @@
...
+	public static final PartModel MODELS_ON = new PartModel( MODEL_BASE, MODEL_STATUS_ON );
```
Comment (orod-org) [inline src/main/java/appeng/parts/misc/PartInvertedToggleBus.java]: BLOCKER "MODELS_ON" is the name of a field in "PartToggleBus". [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS2387)

File: src/main/java/appeng/parts/misc/PartInvertedToggleBus.java [hunk 7]
```diff
@@ -19,26 +19,24 @@
...
+	public static final PartModel MODELS_HAS_CHANNEL = new PartModel( MODEL_BASE, MODEL_STATUS_HAS_CHANNEL );
```
Comment (orod-org) [inline src/main/java/appeng/parts/misc/PartInvertedToggleBus.java]: BLOCKER "MODELS_HAS_CHANNEL" is the name of a field in "PartToggleBus". [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS2387)

**Comment by orod-org** [comment]
SonarQube analysis reported 92 issues
* BLOCKER 4 blocker
* MAJOR 50 major
* MINOR 27 minor
* INFO 11 info

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. MAJOR [AEBaseBlock.java#L444](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/2ed3c954b4944094eef2b07d4abc879baf4cdfb2/src/main/java/appeng/block/AEBaseBlock.java#L444): There is an apparent infinite recursive loop in appeng.block.AEBaseBlock.getOrientable(IBlockAccess, BlockPos) [rule](https://sonar.orod.org/coding_rules#rule_key=findbugs%3AIL_INFINITE_RECURSIVE_LOOP)
1. MAJOR [BlockCableBus.java#L239](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/2ed3c954b4944094eef2b07d4abc879baf4cdfb2/src/main/java/appeng/block/networking/BlockCableBus.java#L239): appeng.block.networking.BlockCableBus.getPickBlock(IBlockState, RayTraceResult, World, BlockPos, EntityPlayer) may return null, but is declared @Nonnull [rule](https://sonar.orod.org/coding_rules#rule_key=findbugs%3ANP_NONNULL_RETURN_VIOLATION)
1. MAJOR [AEBaseGui.java#L524](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/2ed3c954b4944094eef2b07d4abc879baf4cdfb2/src/main/java/appeng/client/gui/AEBaseGui.java#L524): Method appeng.client.gui.AEBaseGui.handleMouseClick(Slot, int, int, ClickType) orders expressions in a conditional in a sub optimal way [rule](https://sonar.orod.org/coding_rules#rule_key=fb-contrib%3ASEO_SUBOPTIMAL_EXPRESSION_ORDER)
1. MAJOR [AEBaseGui.java#L740](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/2ed3c954b4944094eef2b07d4abc879baf4cdfb2/src/main/java/appeng/client/gui/AEBaseGui.java#L740): Remove this silly call to "Math.floor" [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS2185)
1. MAJOR [CableBusBakedModel.java#L114](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/2ed3c954b4944094eef2b07d4abc879baf4cdfb2/src/main/java/appeng/client/render/cablebus/CableBusBakedModel.java#L114): Method appeng.client.render.cablebus.CableBusBakedModel.getQuads(IBlockState, EnumFacing, long) allocates an object that is used in a constant way in a loop [rule](https://sonar.orod.org/coding_rules#rule_key=fb-contrib%3APCAIL_POSSIBLE_CONSTANT_ALLOCATION_IN_LOOP)
1. MAJOR [CableBusBakedModel.java#L142](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/2ed3c954b4944094eef2b07d4abc879baf4cdfb2/src/main/java/appeng/client/render/cablebus/CableBusBakedModel.java#L142): appeng.client.render.cablebus.CableBusBakedModel.isStraightLine(AECableType, EnumMap) makes inefficient use of keySet iterator instead of entrySet iterator [rule](https://sonar.orod.org/coding_rules#rule_key=findbugs%3AWMI_WRONG_MAP_ITERATOR)
1. MAJOR [CableBusBakedModel.java#L212](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/2ed3c954b4944094eef2b07d4abc879baf4cdfb2/src/main/java/appeng/client/render/cablebus/CableBusBakedModel.java#L212): appeng.client.render.cablebus.CableBusBakedModel.addCableQuads(CableBusRenderState, List) makes inefficient use of keySet iterator instead of entrySet iterator [rule](https://sonar.orod.org/coding_rules#rule_key=findbugs%3AWMI_WRONG_MAP_ITERATOR)
1. MAJOR [BiometricCardBakedModel.java#L177](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/2ed3c954b4944094eef2b07d4abc879baf4cdfb2/src/main/java/appeng/client/render/model/BiometricCardBakedModel.java#L177): Method appeng.client.render.model.BiometricCardBakedModel$1.handleItemState(IBakedModel, ItemStack, World, EntityLivingBase) appears to call the same method on the same object redundantly [rule](https://sonar.orod.org/coding_rules#rule_key=fb-contrib%3APRMC_POSSIBLY_REDUNDANT_METHOD_CALLS)
1. MAJOR [UVLModelLoader.java#L276](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/2ed3c954b4944094eef2b07d4abc879baf4cdfb2/src/main/java/appeng/client/render/model/UVLModelLoader.java#L276): Method appeng.client.render.model.UVLModelLoader$UVLModelWrapper.bake(IModelState, VertexFormat, Function) appears to call the same method on the same object redundantly [rule](https://sonar.orod.org/coding_rules#rule_key=fb-contrib%3APRMC_POSSIBLY_REDUNDANT_METHOD_CALLS)
1. MAJOR [BlockSlabCommon.java#L30](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/2ed3c954b4944094eef2b07d4abc879baf4cdfb2/src/main/java/appeng/decorative/slab/BlockSlabCommon.java#L30): Null passed for non-null parameter of net.minecraft.block.Block.getBlockHardness(IBlockState, World, BlockPos) in new appeng.decorative.slab.BlockSlabCommon(Block) [rule](https://sonar.orod.org/coding_rules#rule_key=findbugs%3ANP_NONNULL_PARAM_VIOLATION)

**Comment by orod-org** [comment]
SonarQube analysis reported 92 issues
* BLOCKER 4 blocker
* MAJOR 50 major
* MINOR 27 minor
* INFO 11 info

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. MAJOR [AEBaseBlock.java#L444](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/33532cbb50537cab59d0fb7b10c2adbb4d772338/src/main/java/appeng/block/AEBaseBlock.java#L444): There is an apparent infinite recursive loop in appeng.block.AEBaseBlock.getOrientable(IBlockAccess, BlockPos) [rule](https://sonar.orod.org/coding_rules#rule_key=findbugs%3AIL_INFINITE_RECURSIVE_LOOP)
1. MAJOR [BlockCableBus.java#L239](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/33532cbb50537cab59d0fb7b10c2adbb4d772338/src/main/java/appeng/block/networking/BlockCableBus.java#L239): appeng.block.networking.BlockCableBus.getPickBlock(IBlockState, RayTraceResult, World, BlockPos, EntityPlayer) may return null, but is declared @Nonnull [rule](https://sonar.orod.org/coding_rules#rule_key=findbugs%3ANP_NONNULL_RETURN_VIOLATION)
1. MAJOR [AEBaseGui.java#L524](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/33532cbb50537cab59d0fb7b10c2adbb4d772338/src/main/java/appeng/client/gui/AEBaseGui.java#L524): Method appeng.client.gui.AEBaseGui.handleMouseClick(Slot, int, int, ClickType) orders expressions in a conditional in a sub optimal way [rule](https://sonar.orod.org/coding_rules#rule_key=fb-contrib%3ASEO_SUBOPTIMAL_EXPRESSION_ORDER)
1. MAJOR [AEBaseGui.java#L740](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/33532cbb50537cab59d0fb7b10c2adbb4d772338/src/main/java/appeng/client/gui/AEBaseGui.java#L740): Remove this silly call to "Math.floor" [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS2185)
1. MAJOR [CableBusBakedModel.java#L114](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/33532cbb50537cab59d0fb7b10c2adbb4d772338/src/main/java/appeng/client/render/cablebus/CableBusBakedModel.java#L114): Method appeng.client.render.cablebus.CableBusBakedModel.getQuads(IBlockState, EnumFacing, long) allocates an object that is used in a constant way in a loop [rule](https://sonar.orod.org/coding_rules#rule_key=fb-contrib%3APCAIL_POSSIBLE_CONSTANT_ALLOCATION_IN_LOOP)
1. MAJOR [CableBusBakedModel.java#L142](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/33532cbb50537cab59d0fb7b10c2adbb4d772338/src/main/java/appeng/client/render/cablebus/CableBusBakedModel.java#L142): appeng.client.render.cablebus.CableBusBakedModel.isStraightLine(AECableType, EnumMap) makes inefficient use of keySet iterator instead of entrySet iterator [rule](https://sonar.orod.org/coding_rules#rule_key=findbugs%3AWMI_WRONG_MAP_ITERATOR)
1. MAJOR [CableBusBakedModel.java#L212](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/33532cbb50537cab59d0fb7b10c2adbb4d772338/src/main/java/appeng/client/render/cablebus/CableBusBakedModel.java#L212): appeng.client.render.cablebus.CableBusBakedModel.addCableQuads(CableBusRenderState, List) makes inefficient use of keySet iterator instead of entrySet iterator [rule](https://sonar.orod.org/coding_rules#rule_key=findbugs%3AWMI_WRONG_MAP_ITERATOR)
1. MAJOR [BiometricCardBakedModel.java#L177](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/33532cbb50537cab59d0fb7b10c2adbb4d772338/src/main/java/appeng/client/render/model/BiometricCardBakedModel.java#L177): Method appeng.client.render.model.BiometricCardBakedModel$1.handleItemState(IBakedModel, ItemStack, World, EntityLivingBase) appears to call the same method on the same object redundantly [rule](https://sonar.orod.org/coding_rules#rule_key=fb-contrib%3APRMC_POSSIBLY_REDUNDANT_METHOD_CALLS)
1. MAJOR [UVLModelLoader.java#L276](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/33532cbb50537cab59d0fb7b10c2adbb4d772338/src/main/java/appeng/client/render/model/UVLModelLoader.java#L276): Method appeng.client.render.model.UVLModelLoader$UVLModelWrapper.bake(IModelState, VertexFormat, Function) appears to call the same method on the same object redundantly [rule](https://sonar.orod.org/coding_rules#rule_key=fb-contrib%3APRMC_POSSIBLY_REDUNDANT_METHOD_CALLS)
1. MAJOR [BlockSlabCommon.java#L30](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/33532cbb50537cab59d0fb7b10c2adbb4d772338/src/main/java/appeng/decorative/slab/BlockSlabCommon.java#L30): Null passed for non-null parameter of net.minecraft.block.Block.getBlockHardness(IBlockState, World, BlockPos) in new appeng.decorative.slab.BlockSlabCommon(Block) [rule](https://sonar.orod.org/coding_rules#rule_key=findbugs%3ANP_NONNULL_PARAM_VIOLATION)

File: src/main/java/appeng/parts/networking/PartCable.java [hunk 8]
```diff
@@ -43,6 +43,7 @@
 import appeng.api.parts.IPart;
 import appeng.api.parts.IPartCollisionHelper;
 import appeng.api.parts.IPartHost;
+import appeng.api.parts.IPartModel;
```
Comment (orod-org) [inline src/main/java/appeng/parts/networking/PartCable.java]: MINOR Remove this unused import 'appeng.api.parts.IPartModel'. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AUselessImportCheck)

File: src/main/java/appeng/client/render/cablebus/CableBusBakedModel.java [hunk 9]
```diff
@@ -122,34 +126,38 @@
...
 		if( !it.hasNext() )
 		{
 			return false; // No connections
 		}
-		EnumFacing firstSide = it.next();
-		AECableType firstType = sides.get( firstSide );
+
+		final Entry<EnumFacing, AECableType> nextConnection = it.next();
+		final EnumFacing firstSide = nextConnection.getKey();
+		final AECableType firstType = nextConnection.getValue();
```
Comment (orod-org) [inline src/main/java/appeng/client/render/cablebus/CableBusBakedModel.java]: MAJOR Move the declaration of "firstType" closer to the code that uses it. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS1941)

**Comment by orod-org** [comment]
SonarQube analysis reported 90 issues
* BLOCKER 4 blocker
* MAJOR 48 major
* MINOR 28 minor
* INFO 10 info

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. MAJOR [AEBaseBlock.java#L444](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/b33ec9798bd9e9b316dea2f638826c7c7146af8a/src/main/java/appeng/block/AEBaseBlock.java#L444): There is an apparent infinite recursive loop in appeng.block.AEBaseBlock.getOrientable(IBlockAccess, BlockPos) [rule](https://sonar.orod.org/coding_rules#rule_key=findbugs%3AIL_INFINITE_RECURSIVE_LOOP)
1. MAJOR [BlockCableBus.java#L239](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/b33ec9798bd9e9b316dea2f638826c7c7146af8a/src/main/java/appeng/block/networking/BlockCableBus.java#L239): appeng.block.networking.BlockCableBus.getPickBlock(IBlockState, RayTraceResult, World, BlockPos, EntityPlayer) may return null, but is declared @Nonnull [rule](https://sonar.orod.org/coding_rules#rule_key=findbugs%3ANP_NONNULL_RETURN_VIOLATION)
1. MAJOR [AEBaseGui.java#L524](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/b33ec9798bd9e9b316dea2f638826c7c7146af8a/src/main/java/appeng/client/gui/AEBaseGui.java#L524): Method appeng.client.gui.AEBaseGui.handleMouseClick(Slot, int, int, ClickType) orders expressions in a conditional in a sub optimal way [rule](https://sonar.orod.org/coding_rules#rule_key=fb-contrib%3ASEO_SUBOPTIMAL_EXPRESSION_ORDER)
1. MAJOR [AEBaseGui.java#L740](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/b33ec9798bd9e9b316dea2f638826c7c7146af8a/src/main/java/appeng/client/gui/AEBaseGui.java#L740): Remove this silly call to "Math.floor" [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS2185)
1. MAJOR [CableBusBakedModel.java#L115](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/b33ec9798bd9e9b316dea2f638826c7c7146af8a/src/main/java/appeng/client/render/cablebus/CableBusBakedModel.java#L115): Method appeng.client.render.cablebus.CableBusBakedModel.getQuads(IBlockState, EnumFacing, long) allocates an object that is used in a constant way in a loop [rule](https://sonar.orod.org/coding_rules#rule_key=fb-contrib%3APCAIL_POSSIBLE_CONSTANT_ALLOCATION_IN_LOOP)
1. MAJOR [CableBusBakedModel.java#L217](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/b33ec9798bd9e9b316dea2f638826c7c7146af8a/src/main/java/appeng/client/render/cablebus/CableBusBakedModel.java#L217): appeng.client.render.cablebus.CableBusBakedModel.addCableQuads(CableBusRenderState, List) makes inefficient use of keySet iterator instead of entrySet iterator [rule](https://sonar.orod.org/coding_rules#rule_key=findbugs%3AWMI_WRONG_MAP_ITERATOR)
1. MAJOR [BiometricCardBakedModel.java#L177](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/b33ec9798bd9e9b316dea2f638826c7c7146af8a/src/main/java/appeng/client/render/model/BiometricCardBakedModel.java#L177): Method appeng.client.render.model.BiometricCardBakedModel$1.handleItemState(IBakedModel, ItemStack, World, EntityLivingBase) appears to call the same method on the same object redundantly [rule](https://sonar.orod.org/coding_rules#rule_key=fb-contrib%3APRMC_POSSIBLY_REDUNDANT_METHOD_CALLS)
1. MAJOR [UVLModelLoader.java#L276](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/b33ec9798bd9e9b316dea2f638826c7c7146af8a/src/main/java/appeng/client/render/model/UVLModelLoader.java#L276): Method appeng.client.render.model.UVLModelLoader$UVLModelWrapper.bake(IModelState, VertexFormat, Function) appears to call the same method on the same object redundantly [rule](https://sonar.orod.org/coding_rules#rule_key=fb-contrib%3APRMC_POSSIBLY_REDUNDANT_METHOD_CALLS)
1. MAJOR [BlockSlabCommon.java#L30](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/b33ec9798bd9e9b316dea2f638826c7c7146af8a/src/main/java/appeng/decorative/slab/BlockSlabCommon.java#L30): Null passed for non-null parameter of net.minecraft.block.Block.getBlockHardness(IBlockState, World, BlockPos) in new appeng.decorative.slab.BlockSlabCommon(Block) [rule](https://sonar.orod.org/coding_rules#rule_key=findbugs%3ANP_NONNULL_PARAM_VIOLATION)
1. MAJOR [BlockSlabCommon.java#L30](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/b33ec9798bd9e9b316dea2f638826c7c7146af8a/src/main/java/appeng/decorative/slab/BlockSlabCommon.java#L30): Null passed for non-null parameter of net.minecraft.block.Block.getBlockHardness(IBlockState, World, BlockPos) in new appeng.decorative.slab.BlockSlabCommon(Block) [rule](https://sonar.orod.org/coding_rules#rule_key=findbugs%3ANP_NONNULL_PARAM_VIOLATION)
